### ISSUE TITLE
Errors during compilation after updating Armory3D - Update SDK

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2945] opened 2023-10-12 09:58 UTC
Thank you for contributing to Armory!

**Description**
Errors during compilation after updating Armory3D - Update SDK

D:\Armory3D\SDK\ArmorySDK2310\armsdk/nodejs/node.exe D:\Armory3D\SDK\ArmorySDK2310\armsdk/Kha/make krom -g direct3d11 --shaderversion 330 --parallelAssetConversion 4 --to build_test/debug --quiet
Traceback (most recent call last):
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\props_ui.py", line 1182, in invoke
    return self.execute(context)
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\props_ui.py", line 1205, in execute
    make.play()
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 595, in play
    compile(assets_only=(not wrd.arm_recompile))
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 404, in compile
    state.proc_build = run_proc(cmd, build_done)
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 81, in run_proc
    p = subprocess.Popen(cmd)
  File "D:\Armory3D\Blender\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Armory3D\Blender\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
Error: Python: Traceback (most recent call last):
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\props_ui.py", line 1182, in invoke
    return self.execute(context)
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\props_ui.py", line 1205, in execute
    make.play()
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 595, in play
    compile(assets_only=(not wrd.arm_recompile))
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 404, in compile
    state.proc_build = run_proc(cmd, build_done)
  File "D:\Armory3D\SDK\ArmorySDK2310\armsdk/armory\blender\arm\make.py", line 81, in run_proc
    p = subprocess.Popen(cmd)
  File "D:\Armory3D\Blender\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Armory3D\Blender\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku

**To Reproduce**
updating Armory3D (2023.10.0) - Update SDK

**Expected behavior**
No errors :)

**System**
Blender: 3.6.4
Armory: 2023.10.0
OS: Windows 11 Pro PL
Graphics card: GTX 1070 8GB

[Error.zip](https://github.com/armory3d/armory/files/12879993/Error.zip)

**Comment by rpaladin** [comment] 2023-10-12 16:02
`Blender 2.6.4?` I think you meant `Blender 3.6.4`?

Anyhow, I get this error a lot myself I believe. Refreshing Blender after reinstalling / updating Armory via Git usually solves the issue.

**Comment by vmitro** [comment] 2023-10-12 19:05
Install the Armory Blender addon again.

**Comment by Dzynek** [comment] 2023-10-13 07:58
I forgot I did in Blender: File -> Default -> Load Factory Setting

**Comment by rpaladin** [comment] 2023-10-13 20:29
If the issue is resolved, perhaps consider closing this issue?

**Closed** 2023-10-14 09:43 UTC
Labels: bug
