### ISSUE TITLE
Bundling scripts in *.blend file

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#128] opened 2017-02-03 23:54 UTC
Is it already supported? I'm using Preview 6, goto File -> External Data and use 'Pack all into .blend' or 'Automatically pack into .blend', copy the blend file and open it again, but no scripts are available.

**Comment by arturjpv** [comment] 2017-02-04 11:04
Hi @sh-dave,

Really interesting question that arises even more questions from my part. I was thinking about this at the same moment you post it. But I needed to do some checks before posting. Let me explain all I have found about this. Maybe you know most of this information, but let me state it just for the purpose of adding some related questions at the end. Of course, these are all assumptions. We will need @luboslenco to point at the wrong ones, to avoid spreading wrong information from my part.

I think this is not supported for now. When looking at the way we can define Armory traits over an object, we can find the following options:

- Logic Nodes - Of course, if you define the logic as nodes, this information will be stored inside the .blend file. Armory will generate a real .hx file on the fly, when playing (building), to implement the real logic in it (based on the logic node information).

- Bundled Script - Bundled Scripts let's you assign an already premade haxe file to the trait. These files are not included in blender. This files are part of the armory sdk, you can find them in "armsdk/armory/Sources/armory/trait". The relationship from the trait to the file is stablished manually when you chose a Class from the list. This string with the name of the class will establish the relationship and amory will get the correct .hx file when playing (building), but these files are not really part of the .blend file.

- Haxe script - Similar to the bundled scripts. You define the relationship to a real .hx file using a Class name reference. The thing here is that these files are not provided, the Class reference will make armory to look for the real .hx file in the project structure defined in Render data block -> Armory Project: Package (package name for scripts). By default this is the "arm" folder that appears alongside the main .blend file. 

- Python Script and Js Script - These options lets you choose a text data block from the .blend file. This text is really bundled in the .blend file, as is part of the .blend data.

As I seem not to find a way to relate a blender text data block with a haxe script (like we can do with Python and Js) I think this is not supported for now. I don't know if this is going to be a previous feature before supporting .hx files inside blender. This would be really interesting as we are also using packaged textures. And my related questions are:

- Even if the option of packaging scripts is not available for the future, are we going to be able to relate blender text data blocks with haxe scripts? This means, being able to write haxe code inside blender and relating it in the traits dialog.

- Is the armory api for the three languages (Python, JS and Haxe) going to be equally expressive? By equally expressive I mean if we can accomplish the same things in the three languages, or if some things can be done only from external haxe files and the Python and JS bundled scripts can't be used for some things. If the three API bindings are going to be equally expressive, we already can have scripts bundled inside blender, buy not using haxe (only Python and JS). I still need to explore the armory API so I can't say anything about this for now.

**Comment by sh-dave** [comment] 2017-02-04 11:54
Hi @arturjpv, thanks for your input.

I should probably have stated that i'm only interested and tested with haxe scripts.
Thinking about it a bit further, bundling probably only makes sense for simple test projects.

Instead of it, i think it would make more sense to be able to specify additional "include paths" for scripts.
So one can build a couple of utility trait libraries (i'm thinking f.ex. like a "Platformer" package) you could then actually use in multiple projects.

**Comment by luboslenco** [comment] 2017-02-04 12:35
It is kind of supported but Haxe scripts have to be packed in manually. Blender does not seem to pack external text blocks when 'Pack all into .blend' operator is executed.

There is a 'feature' - if text block name ends with '.hx', it will be written into the project /Sources folder automatically. Add new trait of type 'Haxe Script' - hit 'New Script' - switch to text editor in Blender - hit 'Text - Open Text Block' - open newly created Haxe Script ('Enable filtering of files' has to be disabled for .hx files to appear) - and finally 'Text - Make Internal'. The .hx file is now packed & can be edited within Blender. It will be auto-saved to /Sources dir on build.

Armory could do the packing for .hx files automatically - could be handy for single .blend file distribution of projects, on the other hand sync issues could arise (editing the file externally and not packing it again) and potentially harder to manage projects. Packing is still useful for assets, since you can reference files all over the place. Haxe scripts are always located in local /Sources dir (+armsdk), so packing + cleaning + zipping project folder should always create minimal fully distributable project.

@arturjpv Python & JS & Haxe should be equally powerful in terms of API, the catch is Python & JS scripts will only work for JS targets currently (browser, electron, krom, krom in Blender viewport). This can be resolved in the future but will probably take a while.

@sh-dave That should be useful. A standard Kha's 'project.addLibrary()' could do for including additional sources, just need to figure a clean way of adding libraries and saying 'I wand to use trait X from library Y' form inside Blender. Plus keep it easy to distribute projects with additional libraries.

**Comment by arturjpv** [comment] 2017-02-06 22:27
Hi,

It took me some time to split the mazeball example to try the assets approach. It's interesting to have an object with it's behavior in the same file.

Please, find here the test:  [mazeball_with_assets.zip](https://github.com/armory3d/armory/files/756000/mazeball_with_assets.zip)

The "feature" @luboslenco suggested to embed the .hx files worked. The modified mazeball has the following structure:

<pre>
.
├── assets
│   ├── ball.blend
│   └── maze.blend
├── license.txt
└── mazeball_with_assets.blend
</pre>

First time doing this with armory, so didn't know if this could work. Assets explanation:

- ball.blend - Contains the ball asset with the material and the BallController. It also includes a test platform to help while programming the behavior (this is an assumption - something like a unit test).

- maze.blend - Contains the maze asset with the material and the MazeController.

- mazeball_with_assets.blend - Just links the two resources and... it works (more or less)! 

Several considerations:

Just opening the blend and hitting play does not work because armory is not able to create the "arm" folder. Armory creates the "Sources" folder but is not able to create the "arm" folder to extract the embedded .hx files. This happens also when opening the assets independently.

The other problem is that the function that tries to get the "Finish" object is not working. It seems is not working with linked objects. As soon as I made the linked "Finish" data block local worked again. I modified the BallController to protect the null access caused by failing to get the "Finish" object.

Another thing to take into account when linking the object is that this brings in object data, mesh and material with textures but not the text data block, we need to remember to link the text data block in addition.

I'm interested in this or similar approaches because we need to find a way to scale the number of resources.

**Comment by luboslenco** [comment] 2017-02-10 00:13
@arturjpv This is madness - really cool!
- I fixed creating of "arm"(or whatever is it set to) package dir.
- The problem with "Finish" object is that Armory adds a postfix to object name when it is linked from different blend. This is to prevent name collisions since Blender allows same names of linked & local objects. In this case the name is "Finish_Lib", since Blender stores it in a library object called 'Lib'. This is really ugly when you want to access objects from scripts, have to figure some a way to handle this.

<img width="273" alt="same_name" src="https://cloud.githubusercontent.com/assets/3685704/22808587/05e85828-ef2d-11e6-8cbc-8ac625611d8e.png">

**Comment by luboslenco** [comment] 2017-08-22 12:32
There is now an example on splitting the assets into multiple blends:
https://github.com/armory3d/armory_examples/tree/master/game_bowling

More issue reports on this matter welcome!

**Closed by luboslenco** 2017-08-22 12:32 UTC
