### ISSUE TITLE
 When the “init” node connects to the “canvas” node and then runs the project, the screen is black 

### ISSUE THREAD

**Issue by haizhou37** [armory3d/armory#1842] opened 2020-09-06 10:24 UTC
**os:deepin 20
cpu:ryzen3 2200g
blender:2.83.5
armorysSDK:2020.9
Even if you create a default new project run, this problem still occur**

![截图录屏_Blender_20200906182055](https://user-images.githubusercontent.com/33272474/92323795-2d948b80-f06e-11ea-8fad-0f809150b0c7.gif)

**Comment by MoritzBrueckner** [comment] 2020-09-06 13:48
Is there an error when you start Blender from a terminal?

This might be related to https://github.com/armory3d/armory/issues/1181

**Comment by haizhou37** [comment] 2020-09-09 10:50
> Is there an error message when you start Blender from a terminal and run the game?
> 
> This might be related to #1181

![截图录屏_选择区域_20200909184648](https://user-images.githubusercontent.com/33272474/92589538-45b61600-f2cd-11ea-8238-06b47646e510.gif)

**Comment by MoritzBrueckner** [comment] 2020-09-09 21:35
Do you have the canvas trait on an object other than the active camera? If yes, thats the problem and moving it to the active camera or changing the trait to a scene trait will solve the issue.

Nonetheless this should not happen. We should probably restrict Canvas traits to scenes to prevent this. Even if restricted to scenes *and* cameras this could cause problems when the active camera is changed.

**Comment by haizhou37** [comment] 2020-09-10 12:32
> Do you have the canvas trait on an object other than the active camera? If yes, thats the problem and moving it to the active camera or changing the trait to a scene trait will solve the issue. Thanks for reporting this!
> 
> Nonetheless this should not happen. We should probably restrict Canvas traits to scenes to prevent this. Even if restricted to scenes _and_ cameras this could cause problems when the active camera is changed.

Do you mean as shown in the picture? But it's still going to be black
![截图录屏_Navigator_20200910203125](https://user-images.githubusercontent.com/33272474/92729252-a5332500-f3a4-11ea-9738-000c7c03b445.png)

**Comment by MoritzBrueckner** [comment] 2020-09-10 13:53
Did you run a clean build? I can only reproduce this when the canvas trait is on another object other than the active camera or a scene.

If a clean build doesn't help, can you send a test project (including the canvas file) please?

**Comment by haizhou37** [comment] 2020-09-11 11:37
> Did you run a clean build? I can only reproduce this error when the canvas trait is on another object other than the active camera or a scene.
> 
> If a clean build doesn't help, can you send a test project (including the canvas file) please?
[New Folder.zip](https://github.com/armory3d/armory/files/5208654/New.Folder.zip)

**Comment by MoritzBrueckner** [comment] 2020-09-11 13:17
Thanks! This was due to an empty or nonexisting element name (so actually there were two different bugs, the one above with the trait applied to a wrong object and then this) and will be fixed in https://github.com/armory3d/armory/pull/1859.

**Closed** 2020-09-13 08:28 UTC
Labels: bug
