### ISSUE TITLE
Variable of Rotation resets to 0,0,0,1 after cleaning project

### ISSUE THREAD

**Issue by JAWS81** [armory3d/armory#2506] opened 2022-06-23 21:24 UTC
Thank you for contributing to Armory!

**Description**
When setting and printing afterwards of a variable for rotation. The variable is set with the correct values. But after cleaning and restarting the values shown are 0,0,0,1.  

All done with Nodes. Haven´t seen this behavior with vectors or floats yet.

**To Reproduce**
This setup on a default cube.
![grafik](https://user-images.githubusercontent.com/80793695/175402908-563f8f41-e6a7-47ed-afb9-cd0efd83f182.png)

To get the actual values again the print node needs to be connected ones to the "Get rotation" node and then the project needs to be startet again. Cleaning, and the setup can be reconnected to the shown one.

**Expected behavior**
The variable shall be set with the actual rotation. 

**System**
Blender: 2.93.6
Armory:2022-06
OS:Windows 11
Graphics card: RTX2080 Super

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by e2002e** [comment] 2022-06-27 19:52
What's wrong with the factor being at 1 ?

**Comment by MoritzBrueckner** [comment] 2022-07-02 22:08
I can confirm the issue, it seems that the rotation variable node counts its inputs at a point in time where it doesn't have any inputs yet. As a result of this it then prevents values from being written to it.

@niacdoial Hi, can you remember why you added the `input_length` checks in `RotationNode.hx`? Node inputs are added after a node's constructor is called, so I'm wondering if this has worked at all at some point in time.

**Comment by niacdoial** [comment] 2022-07-02 22:26
uuugh, yeah OK, I see.
I think the `input_length` variable itself was needless optimisation (especially since `input.length()` might optimise to a single in-memory fetch as well).

Though TBH I also had/have a very bad understanding of how setting variables is supposed to work in the case where the variable node in question has inputs (or worse, some but not all inputs, which, how to even distinguish this in code since non-value variable nodes create(d) phantom value variable nodes as their inputs).

Every time I look at what I contributed here, I see more jank I've caused you. Sorry.

**Comment by MoritzBrueckner** [comment] 2022-07-02 22:39
All right, so I guess it's safe to remove the checks then. I will try to do that tomorrow.

The rotation node internally always uses a quaternion, right? In this case I think it's also possible to simply copy the quaternion instead of setting all the values of the connected input nodes, since as far as I know the inputs are only meant to be used for initialization. What irritates me is that the other variable nodes also have some code that looks like the inputs should be updated as well (see [this](https://github.com/armory3d/armory/blob/2252c31a396dc74c09c22930df1611c8e5e3b334/Sources/armory/logicnode/FloatNode.hx#L18) for example). I'm not sure what to do here, I will bring up this discussion on Discord.

> Every time I look at what I contributed here, I see more jank I've caused you. Sorry.

I think the same about my code, it's normal ;) You contributed great features!

**Comment by niacdoial** [comment] 2022-07-02 23:06
> The rotation node internally always uses a quaternion, right?
Yep!

If the inputs are only meant for initialization, this means that the nodes can't be used to convert/assemble values which change over time right?
I think there was a demo (or a PR?) trying to separate variables (like "Vector variable") from conversions (like "Combine XYZ") by making them separate nodes, and stripping the values from the variable nodes?
It *does* remove the ability to directly initialize them, but maybe it would be the lesser of two evils here? Especially with the "On init" node which can be used for initializations separately.

**Comment by MoritzBrueckner** [comment] 2022-07-03 16:45
This issue should be fixed with https://github.com/armory3d/armory/pull/2513 :)

> If the inputs are only meant for initialization, this means that the nodes can't be used to convert/assemble values which change over time right?

Yes, but I was wrong, the input sockets aren't just for initialization (see the recent discussion in `#armory-dev` on the Discord). 

There is still one problem however with the current approach of using the input sockets to store the rotation: because the quaternion gets composed/decomposed with floating point precision for each read/write, the stored value will slowly change over time even if the same operation is done over and over. I'm not sure how to solve this, but for now it's not a big priority I think.

**Closed** 2022-07-04 11:27 UTC
Labels: bug, logic nodes
