### ISSUE TITLE
Unable to manually install Armory SDK

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#1228] opened 2019-03-26 19:39 UTC
I am trying to manually install the Armory SDK through Python in a newer version of Blender 2.8 than the version that the SDK comes with. But I get the following errors:

```
Error: Traceback (most recent call last):
  File "/home/amir/.config/blender/2.80/scripts/addons/armory.py", line 205, in execute
    start.register(local_sdk=local_sdk)
  File "/home/amir/Desktop/armory/blender-2.80/armsdk//armory/blender/start.py", line 22, in register
    arm.props_traits_props.register()
  File "/home/amir/Desktop/armory/blender-2.80/armsdk//armory/blender/arm/props_traits_props.py", line 36, in register
    bpy.utils.register_class(ArmTraitPropList)
RuntimeError: Error: 'ArmTraitPropList' doesn't contain '_UL_' with prefix & suffix


location: /home/amir/Desktop/armory/blender-2.80/2.80/scripts/modules/bpy/ops.py:200


Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/amir/Desktop/armory/blender-2.80/2.80/scripts/modules/bpy/ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/amir/.config/blender/2.80/scripts/addons/armory.py", line 205, in execute
    start.register(local_sdk=local_sdk)
  File "/home/amir/Desktop/armory/blender-2.80/armsdk//armory/blender/start.py", line 22, in register
    arm.props_traits_props.register()
  File "/home/amir/Desktop/armory/blender-2.80/armsdk//armory/blender/arm/props_traits_props.py", line 36, in register
    bpy.utils.register_class(ArmTraitPropList)
RuntimeError: Error: 'ArmTraitPropList' doesn't contain '_UL_' with prefix & suffix


location: /home/amir/Desktop/armory/blender-2.80/2.80/scripts/modules/bpy/ops.py:200
```

And here are the steps I followed to install it:

1- copy Armory sdk into Blender’s directory
2- Execute the following commands in Blender’s Python console:

```
bpy.ops.preferences.addon_install(filepath='armsdk/armory/blender/addon/armory.py')
bpy.ops.preferences.addon_enable(module='armory')
user_prefs = bpy.context.preferences
addon_prefs = user_prefs.addons['armory'].preferences
addon_prefs.sdk_path = 'armsdk'
bpy.ops.arm_addon.start() #this throws and error
```

@luboslenco  Am I doing something wrong?

**Comment by luboslenco** [comment] 2019-03-26 19:46
Don't think you are doing anything wrong, armory addon will need more updating for latest Blender. Will try to take care of it asap.

**Comment by Amir-Arsalan** [comment] 2019-03-26 20:13
@luboslenco Would appreciate if you can upload a new version of the addon on Armory website. Like 0.6a or something. I'm using the 0.6 SDK now.

**Comment by zicklag** [comment] 2019-03-26 22:22
I can confirm that it has to do with the latest Blender. Armory and a few other plugins I have ( even ones that come with Blender ) are giving similar errors. It looks like they are now enforcing a naming scheme for classes that requires them to be prefixed with `ALPHANUMERICPREFIX_CLASSTYPEINDICATOR` like `ARM_UL_PropList`. I tested renaming one of the classes, and it looks like it stopped complaining, but it then moved on to another class. We probably just need to go through and rename all of them.

**Comment by BlackGoku36** [comment] 2019-03-27 06:04
I will try to fix today if I can 👍

**Comment by luboslenco** [comment] 2019-03-28 21:56
If anyone is actively looking into this please let me know so we can prevent duplicate work, otherwise I will assign it to myself. 🙂

**Comment by Amir-Arsalan** [comment] 2019-03-29 12:07
@BlackGoku36 @zicklag I think @luboslenco was talking to you guys :grin:

**Comment by BlackGoku36** [comment] 2019-03-29 13:23
@luboslenco I am doing it right now 👍 , @Amir-Arsalan  I Know 😄

**Comment by BlackGoku36** [comment] 2019-03-29 13:59
There ya go: https://github.com/armory3d/armory/pull/1236 🎊

**Comment by Amir-Arsalan** [comment] 2019-03-29 15:38
@BlackGoku36  Thank you ^_^ 
@luboslenco Do you think it would be possible for you to compile the current stuff and upload it on armory3d.org? Like version 0.6a or something?

**Comment by Amir-Arsalan** [comment] 2019-03-31 23:06
@luboslenco Or would it be possible to provide compiled version of the Armory SDK after this commit? Unfortunately it looks like I cannot update Armory SDK on our servers because I do not have write access ... . Would greatly appreciate if you can provide a link for the updated SDK at least.

**Closed** 2019-04-01 10:26 UTC

**Comment by luboslenco** [comment] 2019-04-01 10:54
Yes should be very possible, will try to put up an updated build soon.
