### ISSUE TITLE
Vertex Animation

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armory#1495] opened 2019-12-01 22:11 UTC
Pls it seems Armory3d does not support vertex animation.
Pls try and implement it.

**Comment by MoritzBrueckner** [comment] 2021-09-27 15:18
Possible duplicate of https://github.com/armory3d/armory/issues/225. @divineniiquaye what exactly do you mean with vertex animation? Something like shape keys in Blender?

**Comment by MoritzBrueckner** [comment] 2021-11-06 17:40
Closing this as shape keys are now implemented in https://github.com/armory3d/armory/pull/2375.

**Closed by MoritzBrueckner** 2021-11-06 17:40 UTC
Labels: feature request
