### ISSUE TITLE
Logic Nodes aren't connecting to the object

### ISSUE THREAD

**Issue by Zeph-dev** [armory3d/armory#783] opened 2018-07-25 09:35 UTC
When I use the Logic Bricks and connect it with an object, I build it, and it desn't do anything, or the object simply disappears. I use Blender 2.79, with Armory as an add-on. I'm not entirely sure on how to install it, but it seemed to work, but it just doesn't do anything when I make a build.

Please tell me if there is something I'm doing wrong or if this has already been asked, I'm still learning how to use GitHub. 

TIA,
Zeph

**Comment by Simonrazer** [comment] 2018-07-26 04:36
Please include the .blend in a .zib so the problem is easier to see

**Comment by Zeph-dev** [comment] 2018-07-26 14:12
Ah sorry, my bad, I didn't connect the nodes to the object properly. It works fine now! :)

**Comment by gamergamesz** [comment] 2018-07-27 03:09
Close the issue then

**Closed** 2018-07-27 09:36 UTC
