### ISSUE TITLE
Array Loop with Remove Object - deletes half of the objects (Logic Node)

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2182] opened 2021-05-04 20:53 UTC
Thank you for contributing to Armory!

**Description**
Array Loop width Remove Object - deletes half of the objects

**To Reproduce**
![image](https://user-images.githubusercontent.com/39986875/117068233-4f443080-ad2b-11eb-9077-209692e5c2fb.png)
deletes half of the objects
![image](https://user-images.githubusercontent.com/39986875/117067813-c3320900-ad2a-11eb-856a-b49e6f7d49c1.png)
deletes half of the objects
![image](https://user-images.githubusercontent.com/39986875/117067874-d8a73300-ad2a-11eb-835b-bd767a1b0209.png)

**Expected behavior**
Remove all objects in the array loop

**System**
Blender: 2.83.13 LTS
Armory: 2021.05 and 2021.04
OS: Windows 10 64 bit
Graphics card: Geforce RTS 2060 Super

**Test File**
[ArrayObjectRemove.zip](https://github.com/armory3d/armory/files/6423862/ArrayObjectRemove.zip)

**Comment by MoritzBrueckner** [comment] 2021-05-04 21:42
This is probably caused by the fact that the array of objects is changed while iterating over it.

An example:
We're at index 0 while iterating over an array with two elements. Now we delete the object at that index and as a result, the next object in the array (still at index 1) fills the new gap and is now at index 0. Then, we increment the index variable to 1 but because the object at index 1 is now at index 0, the iteration stops because the end of the array was reached. This results in the skipping of every other object.

So I think that there is not much we can do about. Depending on what you want to achieve, a possible solution could be to add all objects that should be deleted to another array and then iterate over that while deleting from the original array. Then you can clear the temporary array afterwards.

Another idea which we could implement for logic nodes would be a custom iterator with that supports dynamic removal and addition. But because you would have to call `remove()` etc. on this iterator instead of the array, this would probably require a change of the nodes UI and functionality (and even Iron) and might not be possible in this situation. But actually, this could be a good solution for the issue with double execution for paused traits... 🤔

**Comment by Dzynek** [comment] 2021-05-06 09:50
Hello, thanks for the answer

I tried different Logic Nodes configurations

![image](https://user-images.githubusercontent.com/39986875/117277383-21143d00-ae60-11eb-9da8-920bac199c86.png)
It also removes half of the objects

![image](https://user-images.githubusercontent.com/39986875/117277461-31c4b300-ae60-11eb-8f34-a92967bbc35b.png)
It also removes half of the objects

![image](https://user-images.githubusercontent.com/39986875/117277515-3f7a3880-ae60-11eb-9d1a-f1623f653b62.png)
It also removes half of the objects

![image](https://user-images.githubusercontent.com/39986875/117277597-4f921800-ae60-11eb-8ebe-17c6c46b125d.png)
It also removes half of the objects

![image](https://user-images.githubusercontent.com/39986875/117277648-5b7dda00-ae60-11eb-8360-3f1f994b0c47.png)
```
Sources/armory/logicnode/PrintNode.hx:13: Test: 0
Sources/armory/logicnode/PrintNode.hx:13: Test: 1
Sources/armory/logicnode/PrintNode.hx:13: Test: 2
Sources/armory/logicnode/ArrayGetNode.hx:23: Logic error (object: Empty, trait: Test): Array Get - index out of range
Sources/armory/logicnode/PrintNode.hx:13: Test: 3
Sources/armory/logicnode/ArrayGetNode.hx:23: Logic error (object: Empty, trait: Test): Array Get - index out of range
Sources/armory/logicnode/PrintNode.hx:13: Test: 4
```

![image](https://user-images.githubusercontent.com/39986875/117277891-8ec06900-ae60-11eb-9ae8-3089138f2e1b.png)
It works

[ArrayObjectRemove2.zip](https://github.com/armory3d/armory/files/6433510/ArrayObjectRemove2.zip)

**Comment by MoritzBrueckner** [comment] 2021-05-06 17:17
The first few variants all still remove stuff from the array while iterating over, even if there are some logic nodes in between.

The variant where you copy the array to a variable first is the same: the array is not copied, the newly created variable just points to the memory where the array is stored, so any change to the new array will also change the old array. You'd have to copy it first.

The logic tree that creates the error has the same problem with deleting objects while iterating, but it makes things even worse as it uses the length of the array at the time before it was modified. I think it should be documented that the loop node sets the range once and doesn't modify it while iterating (which is usually good).

Also, we should probably add a hint to the wiki that you shouldn't change arrays while iterating over it as well as variables might not always copy the data depending on the type. What do you think of a new troubleshooting/tips and tricks page for logic nodes? Or should this be written somewhere else?

**Comment by MoritzBrueckner** [comment] 2021-05-06 18:55
I've added a new wiki page documenting some of the encountered behaviour: https://github.com/armory3d/armory/wiki/Common-Mistakes. I guess this issue can be closed as you have found a solution?

**Comment by Dzynek** [comment] 2021-05-07 07:52
> The variant where you copy the array to a variable first is the same: the array is not copied, the newly created variable just points to the memory where the array is stored, so any change to the new array will also change the old array. You'd have to copy it first.

![image](https://user-images.githubusercontent.com/39986875/117415686-e15d5c00-af18-11eb-9597-3513f64edad2.png)
Works thanks :)

> I've added a new wiki page documenting some of the encountered behaviour: https://github.com/armory3d/armory/wiki/Common-Mistakes.

I don't know much, but it's probably a nice idea

> I guess this issue can be closed as you have found a solution?

Yes

[ArrayObjectRemove3.zip](https://github.com/armory3d/armory/files/6439944/ArrayObjectRemove3.zip)

**Closed** 2021-05-07 08:46 UTC
Labels: bug, logic nodes
