### ISSUE TITLE
X Error of failed request with default cube scene in Krom and Linux

### ISSUE THREAD

**Issue by Sanva** [armory3d/armory#1909] opened 2020-10-03 10:06 UTC
**Description**
I've just updated Armory today to git version and now a default scene won't run, not with Krom in Linux nor exporting the project to Linux (C).

In both cases the application crashes on startup with the message:

```
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x0
  Serial number of failed request:  14
  Current serial number in output stream:  14
```

This looks like an issue in Kha/Kore, but maybe only with Armory/Kha, because with Kha from Kode/Kha git version I'm able to compile and run applications with Krom in the same system — but I can't compile to C/C++ directly with Kode/Kha from some commits ago because of compilation errors, so I can't test native with that.

**To Reproduce**
Just playing a (saved) default scene.

**Expected behavior**
Scene working just fine.

**System**
Blender: 2.83.4
Armory: Git version.
OS: Linux Mint 19.2 (linux 4.15.0-118-generic x86_64)
Graphics card: NVIDIA Quadro M2000M 4 GB

**Comment by N8n5h** [comment] 2020-10-03 12:45
I'm unable to reproduce with
Blender: 2.83.4
Armory: Git version
OS: Ubuntu 20.04.1LTS (Linux 5.4.0-48-generic)
Graphics card: AMD RX 480 (amd-gpu-pro driver)

Maybe the issue is Xorg / nvidia specific?

**Comment by Sanva** [comment] 2020-10-03 17:31
> Maybe the issue is Xorg / nvidia specific?

Maybe... I'm not sure what to look for :confused: 

But, more info: Using Armory SDK 2020.10 I have the same error, but with Armory SDK 2020.09 the default scene works fine in the same machine, both with Krom and Linux (C).

**Comment by knowledgenude** [comment] 2020-10-03 18:03
A similar issue: https://github.com/lahwaacz/sxlock/issues/4

**Comment by Sanva** [comment] 2020-10-03 18:26
Indeed @knowledgenude ! :smiley: — looks like _exactly_ the same. It turns out I had no display selected as primary in my mutimonitor xrandr setup... selecting one of them fixes this.

Thanks a lot!

**Comment by knowledgenude** [comment] 2020-10-03 23:41
I am reopening the issue because another reference to this was posted in the forum: https://forums.armory3d.org/t/linux-krom-doesnt-compile-in-sdk-2010/4252

This also is happening in Fedora 32/33b with AMD.

**Comment by MoritzBrueckner** [comment] 2020-10-05 14:40
Looks like it could be fixed by this PR from Lubos: https://github.com/Kode/Kinc/pull/562

**Comment by luboslenco** [comment] 2020-10-06 18:27
Any luck with the latest git version? https://github.com/Kode/Kinc/pull/562 is now applied.

**Comment by knowledgenude** [comment] 2020-10-06 18:40
Updated to git version now and for me the problem still. It is a different message from the first one above (instead of `invalid Crtc parameter` i got `invalid Output parameter`).

```
__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.004800319671630859
Finished in 3.462407350540161
X Error of failed request:  BadRROutput (invalid Output parameter)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  9 (RRGetOutputInfo)
  Serial number of failed request:  13
  Current serial number in output stream:  13

```

**Comment by luboslenco** [comment] 2020-10-07 08:25
Another fix incoming by dave at https://github.com/Kode/Kinc/pull/563.

**Comment by luboslenco** [comment] 2020-10-08 09:55
Any luck with the latest git version? https://github.com/Kode/Kinc/pull/563 is now applied. 🔥

**Comment by knowledgenude** [comment] 2020-10-08 10:25
It is working fine now, many thanks!

**Closed by knowledgenude** 2020-10-08 10:25 UTC
Labels: bug
