### ISSUE TITLE
Artifacts when using Deferred Low and the Krom runtime (viewport and popup window)

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#171] opened 2017-05-13 09:08 UTC
If I have the camera set to Deferred Low with Krom runtime, I get squares. I also get the squares in the viewport.  Switching to Forward rendering works. It also works with Deferred and the Electron and Browser runtimes.
[scene1.zip](https://github.com/armory3d/armory/files/998462/scene1.zip)

Screenshot:
![armory_artifacts](https://cloud.githubusercontent.com/assets/12836886/26024164/3c27f67c-379a-11e7-9612-30cb7fccbd33.png)

**Comment by luboslenco** [comment] 2017-05-13 09:16
Is this on gtx 1080? Is it ok when you go krom runtime + deferred  + spot lamp instead of point?

For some reason I can not reproduce this but it seems to be caused by cubemap used for capturing shadows for point lamp. Hearing that it works in browser helps, I will look for disparity in cubemap code compared to native.

**Comment by fractalfederation** [comment] 2017-05-13 09:20
Yep, using 1080. I switched from point to spot and it works.

**Comment by luboslenco** [comment] 2017-05-24 07:59
Possibly also fixed now.

**Closed** 2017-06-19 12:00 UTC
