### ISSUE TITLE
Build project in background mode

### ISSUE THREAD

**Issue by tong** [armory3d/armory#2237] opened 2021-06-22 14:36 UTC
**Description**
Building a project in blender background mode throws:
```sh
Finished in 3.385s
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tong/sdk/armsdk//armory/blender/arm/make.py", line 35, in fn
    done()
  File "/home/tong/sdk/armsdk//armory/blender/arm/make.py", line 443, in build_done
    bpy.data.worlds['Arm'].arm_recompile = False
KeyError: 'bpy_prop_collection[key]: key "Arm" not found'
```

**To Reproduce**
`blender -b test.blend --python build.py`

build.py:
```py
import bpy
bpy.ops.arm.publish_project()
```

**Comment by tong** [comment] 2021-06-22 14:50
Here https://github.com/tong/armory/commit/2e5997baa8030428a08c32b8ae20b4dd3d727b03 is a fix for this, but it skips `build_success()`.
Not sure why this error happens.

**Comment by MoritzBrueckner** [comment] 2021-06-22 16:44
Hi,

although your fix probably helps with this concrete use case, a missing `Arm` world will likely lead to more problems down the line, so it's best to find the actual cause. Maybe Armory isn't correctly initialized in background mode or the script is executed too early? If I remember correctly, scripts will execute even before Blender initializes OpenGL in non-background mode, so Blender seems to run them very early.

If this is the case and there is no way to initialize Armory prior to running the script, you could try to manually call the corresponding functions in your script, but maybe it can be fixed in Armory.

**Comment by MoritzBrueckner** [comment] 2021-06-23 18:23
I gave it a try and I can't reproduce this. I found another small related bug for which I will soon open a PR, but the `Arm` world does always exist. If I delete it, it will be recreated before the script runs. Does this happen for you for all blend files?

**Comment by tong** [comment] 2021-06-24 10:32
Yes, for me this happens on every background-mode build, non-background is fine, blender never crashes.
The `Arm` world exits up to when `build_done` is called.

**Comment by MoritzBrueckner** [comment] 2021-06-24 11:41
Yes, the world seems to exist and then it is no longer available in build_done. I think this is a threading issue: when Armory calls Khamake and other tools, it does spawn them as a subprocess. To get notified when the process ends (Khamake has finished for example), it creates a thread in `make.run_proc` that waits for the process to end and then it calls a `done` callback.

The problem is that the callback is not executed in the main thread but in the thread that waits for the process. I don't even know why it works in non-background mode, you should not do this in Blender: https://docs.blender.org/api/current/info_gotcha.html#strange-errors-when-using-the-threading-module.

I came up with a solution yesterday but I don't know how good it is:

- If Blender is started in background mode, no threading is used at all and it blocks execution until subprocesses end. I think the only reason for the non-blocking thread is to not freeze the Blender UI. The done callback is then called in the main thread, your build.py hasn't ended yet and all data is still available.

- If Blender is not running in background mode, a timer is set up that polls every 0.25s for all threads if they have completed their work. If a thread is finished, it is joined with the main thread again and then the polling function calls the callback that is stored in a data structure with each thread and then removes this thread from the structure. This approach does only work in non-background mode because Blender doesn't start timers when running from the command line.

I also tried to use Python's async/await functionality but I couldn't get it working so that it is waiting for a process while already returning the process (but that's what the `run_proc` function does).

Another solution would be to improve the callback so that it doesn't access Blender data, but I think this is still potentially bad and prone to errors.

I will still do some tests and try other things but please let me know if the proposed solution sounds good or not.

**Closed** 2021-06-25 06:57 UTC
Labels: bug

**Comment by tong** [comment] 2021-06-25 08:12
Awesome work!
