### ISSUE TITLE
Add Alpha Hashing to Armory

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#655] opened 2018-06-06 21:04 UTC
Alpha hashing is a method that uses alpha clipping with dithering to create illusion of semi-transparent objects. When combined with multisampling and/or TAA, it can create pretty solid looking smoothing for foliage and similar stuff. At the same time, it's based on discarding parts of mesh from rendering like alpha clip so it's easy to implement in deferred. Would be great to have that in Armory.

**Comment by zauberparacelsus** [comment] 2018-06-06 21:08
Duplicate of #219

**Comment by luboslenco** [comment] 2018-06-07 07:14
Merge with https://github.com/armory3d/armory/issues/219.

**Closed by luboslenco** 2018-06-07 07:14 UTC
