### ISSUE TITLE
Radiance and Environment Texture HDRI causes error during compiling

### ISSUE THREAD

**Issue by JAWS81** [armory3d/armory#2344] opened 2021-09-24 19:31 UTC
Thank you for contributing to Armory!

**Description**
When ever I use a HDRI as environment texture or even no input to the background 
and radiance is activated  the following error message occures. See attachement.

This error persists since I started looking into armory3d on beginning of 2020.
I just thought it was gone but during the last time I just used a Hosek/Wilkie sky texture.

But with HDRI or even without any sky texture the message occures.

I get it working when I make changes to the write_probes.py
Here I have to change everything from 
GPU to CPU 
and also set 
cpu_count =1 
Please see:
https://forums.armory3d.org/t/environment-texure-causes-problem/4498/4

**To Reproduce**
On my PC it already happens when I compile the default cube scene without any changes
In the forum it seems not to reproduce on other PC´s.

Can it be the amount of cores?

**Expected behavior**
Compile without error and without the need to manually mess around in the write_probes.py file.

**System**
Blender: 2.93.4
Armory: 2021-9a
OS: Windows10
Graphics card: RTX2080 Super
CPU: AMD Threadripper 3970X

**Test File**
*(drag & drop the zipped .blend file here)
![error1](https://user-images.githubusercontent.com/80793695/134730046-62a7bfce-c558-427d-b709-57a4867b646d.jpg)

*

**Comment by MoritzBrueckner** [comment] 2021-09-25 00:08
Hi, I still can't reproduce this issue using the latest Armory in Blender 2.93 LTS on Windows. I tested it with the envmap.blend file from the [Armory calibration repo](https://github.com/armory3d/armory_calibration) and other files and it works just fine.

Here is the output of `build_envmap/compiled/Assets/envmaps` for that example file and it should look similar in your case:
![Screenshot](https://user-images.githubusercontent.com/17685000/134750627-8f5d0950-ef61-4deb-8e1d-562cf666744c.png)
Can you please check that and post a similar screenshot/list of the generated output directory?

Because in the linked forum thread we wrote about the used CPU cores: does reducing the number of cores that cmft uses still work? I don't know why this should be an issue but who knows... If it really is caused by using too many cores we will need to check whether there exists a maximum core amount or if we should make it configurable and raise a better error message instead so that users can at least adjust it until it works. Also we should open an [cmft issue](https://github.com/dariomanesku/cmft) then even though it looks pretty unmaintained...

**Comment by JAWS81** [comment] 2021-09-25 03:44
Hi,

please find enclose the output. I did´t do any changes.
![Neue Bitmap](https://user-images.githubusercontent.com/80793695/134756633-ca37568e-16b1-41a7-aa7b-d5d4943629e3.jpg)
.

**Comment by JAWS81** [comment] 2021-09-27 04:42
Hi,

I think I narrowed it down to the following line of code.
cpu_count = 32 # multiprocessing.cpu_count()

All ohter lines I set back to orignal ones.

When ever the number exceeds the number of cores your cpu got, in my case 32, the compiling crashes with to above error message. But as long as the number stays below everthing compiles fine.

The statement  multiprocessing.cpu_count() doesn´t at all on my pc. But I´ve checked on an old 4 core PC I have got kicking around, there the original code works perfectly.

Maybe a general limit or making in configurable could be a good solution.

**Comment by MoritzBrueckner** [comment] 2021-09-27 13:13
Interesting, can you please check what `multiprocessing.cpu_count()` returns on your machine?

**Comment by JAWS81** [comment] 2021-09-27 16:42
Hi,

it returns 64.

**Comment by MoritzBrueckner** [comment] 2021-09-27 17:57
Oh, that's a very interesting observation. That could be the reason for this issue then.

According to this [stackoverflow question](https://stackoverflow.com/questions/38194951/multiprocessing-cpu-count-returning-wrong-number-of-cores) `multiprocessing.cpu_count()` does return the sum of all logical and physical processors but we probably only need the physical processors here (not exactly sure what cmft does with that parameter).

The problem is that the Python standard lib doesn't seem to have a function that returns the number of physical processors. There is a library called [psutil](https://github.com/giampaolo/psutil) that can do this but I don't think that it's a good idea to add a whole library as a dependency just for this parameter. Maybe we could get away with `len(os.sched_getaffinity(0))` (can you please test this and let me know what it returns for you?) but I have to do some research first. If you have any ideas please let me know :)

Some further information: https://stackoverflow.com/questions/1006289/how-to-find-out-the-number-of-cpus-using-python/14840102

**Comment by JAWS81** [comment] 2021-09-27 19:13
I tried my best but it is not working. 
After some research I found some statements that this function might not be available on windows machines.

**Comment by JAWS81** [comment] 2021-09-27 19:17
Yes, you are right. It is 32 64.

**Comment by MoritzBrueckner** [comment] 2021-09-27 21:16
So I think I have a fix, feel free to test https://github.com/MoritzBrueckner/armory/commit/c40fd26c20e5627285f8abb10f1435bea401fa70. I will open a PR tomorrow.

If someone on Mac or Linux sees this: please test it! I tested the fix on Windows and on a laggy Ubuntu VM, but for Mac and other Linux distributions I have to rely on what I found on stackoverflow etc.

**Comment by JAWS81** [comment] 2021-09-28 19:11
Hi,

it took some time but I tested it. Unfortunately it´s now throwing another error. Please find the message attached.
![grafik](https://user-images.githubusercontent.com/80793695/135150672-ff8626f8-6b45-4f38-adf9-9bfbbea32d91.png)

**Comment by MoritzBrueckner** [comment] 2021-09-29 18:35
Hmm, that looks like Kraffiti (`sdk_path/Kinc/Tools/kraffiti/kraffiti.exe`, Kincs's tool to convert images) cannot be found and it seems rather unrelated to above changes. Are you sure that your SDK installation is complete?

**Comment by JAWS81** [comment] 2021-09-29 19:54
Hi,

not quite sure what you mean. I downloaded the currrent "Armory3d" from github and unzipped it and changes the path in Blender. That´s usually enough. I also tried to just copy the two files you changed into my working Armory3d. And I also tried just to copy the whole code into the existing files. Always with the same result. But looking into the directory kraffiti is stored a bit deaper in the file structure. (sdk_path/**Kha**/Kinc/Tools/kraffiti/kraffiti.exe. Can this be a reason?

Or do I have to do something different than I did to test this?

**Comment by MoritzBrueckner** [comment] 2021-09-30 17:55
Oh yes you're right, I forgot to add the Kha directory in the path above :) But if that executable exists I don't know why that error should happen... Especially because I didn't change anything related to that in the linked commit above. Are you sure that this only happens when you apply my changes?

Also, can you please print the content of the `kraffiti_path` variable before line 138 in write_probes.py to check if that path is actually correct? Is there any error message before the one above in the console?

Btw, downloading a repository from github usually doesn't include submodules I think, so be aware of that when downloading the entire SDK. If it's just about the armory folder though it should work.

**Comment by JAWS81** [comment] 2021-09-30 19:12
Hi,

sorry for the inconvenience. You are absolutely right, when I just take the code you changed and put that into my working Armory3d write_probes.py file. It works perfectly. 

What I did before hand was I copied the files from the reposity into the folder. Then the write.probes causes this error.
I wanted to avoid messing inside the files so I did it that way. By the way the utils.py is not causing any trouble so far, this file I justed copied into the folder.

Great, thanks for the quick action and your patient with me.

**Comment by MoritzBrueckner** [comment] 2021-10-02 14:41
Should be fixed after https://github.com/armory3d/armory/pull/2352 is merged, thanks for your cooperation :)

**Comment by JAWS81** [comment] 2021-11-04 22:17
Hello me again,

The CPU count might be fixed. But I am not sure as now the error message I posted above still prevents me from testing it in the new Amory202111.

Sorry, but i am unable to post the variable output of of the "kraffiti_path". As I don´t know how. 
Can you please give me some advise how to?

BR J

**Comment by MoritzBrueckner** [comment] 2021-11-06 00:18
Oh, that's not good :/

So you get the exact same error as before ("Das System kann die angegebene Datei nicht finden" which goes back to `write_probes.py`)? Can you please share it again just that I can be sure that there is no small detail that changed?

Regarding the kraffiti path: please add the following to [this empty line](https://github.com/armory3d/armory/blob/93563dbba586a3c664176b2c43330d88b56b70bd/blender/arm/write_probes.py#L130) for example: `print("Kraffiti path:", kraffiti_path)`. Then save the file, restart Blender, re-export the game and check your console for occurrences of `Kraffiti path: some/path/to/kraffiti` and check whether the path is actually correct.

A few other questions:
- Do you use the release from itch.io or the Git version?
- Does [this](https://github.com/armory3d/armory/blob/93563dbba586a3c664176b2c43330d88b56b70bd/blender/arm/write_probes.py#L193) line exist in your Armory SDK and if it does, what's the output if you add `print("CPU count:", cpu_count)` to the line below that (and restart Blender and so on)?

**Comment by JAWS81** [comment] 2021-11-06 08:08
Good morning,

here is the newest output. As you can see the Kraffiti path is shown at top. And it is actually correct.
But the cpu count is not shown anywhere.  Event though I added the print command line.

I don´t think that the cpu count is the reason for this error. As I successfully tested the lines you changed in my working SKD202110.
This error already showed up when I used the Git version during our discussion for testing. 
Now and before I am always using the itch.io versions.

![Neue Bitmap](https://user-images.githubusercontent.com/80793695/140602652-48b2c408-b5e2-4513-b5b0-e516503bf863.jpg)

**Comment by MoritzBrueckner** [comment] 2021-11-06 12:18
Actually it is a different error (the same error but at another place). If you go the call stack a few lines up you can see that it happens from the code executed by `cpu_count = arm.utils.cpu_count(physical_only=True)`, so that's why you don't see the output from the second print statement: the error happens before that when trying to get the CPU count.

What confuses me is that you were able to execute `wmic cpu get NumberOfCores,NumberOfLogicalProcessors` in your command line but the script somehow can't find it in your case. What's the output if you open a command line and enter `where wmic`? This should give you the path where wmic.exe can be found.

**Comment by JAWS81** [comment] 2021-11-06 18:44
I think you are on the right track.

The command "wmic" is not recognized as a command without a previous command.
"SET PATH=C:\Windows\System32\wbem\;%PATH%;"
After entering that wmic worked.

I added this to the Path variable in Windows, which wasn´t, and after restarting blender it seems to work. The HDRI is shown and there was no error message anymore.

**Closed** 2021-11-08 09:13 UTC
Labels: bug
