### ISSUE TITLE
Nishita artifacts depending on sun angle

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2295] opened 2021-08-04 14:24 UTC
In the example the artifacs are on the top of the sky, but they can appear in another specific angles (at "night" only) while the sun is rotating

[nishita.zip](https://github.com/armory3d/armory/files/6931953/nishita.zip)

**Comment by knowledgenude** [comment] 2021-08-04 18:27
That is the top of the sky: 
![Screenshot from 2021-08-04 15-24-33](https://user-images.githubusercontent.com/63247726/128234508-5c619c62-00d8-45d7-9249-24242c746aa3.png)

I thought about precision issue, but if that is the case shouldn't happens also on "day"? At least it is not noticeable, maybe because it is the same color

![Screenshot from 2021-08-04 15-26-27](https://user-images.githubusercontent.com/63247726/128234758-f57cdfaa-a0e9-4c5e-a561-37713c40cc02.png)

**Comment by MoritzBrueckner** [comment] 2021-08-09 14:52
Hi, can you please test if https://github.com/MoritzBrueckner/armory/tree/fix-nishita-LUT fixes the artifacts for you?

**Comment by knowledgenude** [comment] 2021-08-09 17:34
That worked, @MoritzBrueckner ! many thanks for the fix 

I just had to comment this line (221): jAttenuation.exp(jAttenuation.mult(-1));
Because i got an error "Vec3 has no field exp"

**Comment by MoritzBrueckner** [comment] 2021-08-09 18:41
Oh, I forgot that this needs some additions to the Iron Vec3 class. Add this to `Vec3`:

```haxe
public inline function exp(v: Vec3): Vec3 {
	x = Math.exp(v.x);
	y = Math.exp(v.y);
	z = Math.exp(v.z);
	return this;
}
```

Then everything should hopefully work and look the same as before (even a bit better, there is now less visible banding).

**Comment by knowledgenude** [comment] 2021-08-09 19:33
That is strange, after i uncomment the line the artifacts come back... I guess to fix it would be just clamp the sun rotation? It doesn't make any difference at night

I also tried to comment the line that applies dithering but also didn't solved, do you suspect of anything that i can try here?

**Comment by MoritzBrueckner** [comment] 2021-08-09 20:28
Hmm, that's interesting... I thought that the artifacts stem from the fact that the LUT texture contained too large values (there were even INF values in it), which is fixed by this change (it is also a tiny bit faster now). Because I can't reproduce the artifacts: could you please try to run the project with [RenderDoc](https://github.com/armory3d/armory/wiki/debug#renderdoc) and then search for INF/NaN values in the shader?

How it works:
- Launch the game in renderdoc
- Press F12 to make a capture
- Close the game, renderdoc will open that capture
- Then, in the "Event Browser" on the left, try to find an entry that says `DrawIndexed(1584)` and select it, that's the world's draw call.
- Go to the "Texture Viewer" tab
  ![texture viewer tab](https://user-images.githubusercontent.com/17685000/128769275-0b5465f2-222e-4dac-b915-3d730d1a7cd8.png)
- With the right mouse button, click on a pixel in the rendered image that looks wrong, then click on `Debug` on the very right bottom:
  ![Debug button](https://user-images.githubusercontent.com/17685000/128769499-d8bcb0f0-fa23-426c-9097-2f4dc5ee9315.png)
- Go to the source of the fragment shader, and click on `Run forwards to NaN/Inf`. Then please tell me where the debugger takes you.
  ![Run to NaN/Inf](https://user-images.githubusercontent.com/17685000/128769709-5de8c11c-529b-4875-8616-e8764562211e.png)

Hopefully that will give some insight about what's wrong... It looks like undefined behaviour (or a driver issue) because it doesn't happen for me. Maybe someone else can confirm these artifacts?

**Comment by knowledgenude** [comment] 2021-08-09 20:42
I followed the steps from here https://github.com/armory3d/armory/wiki/debug#renderdoc , but i couldn't open it in RenderDoc: 
![Screenshot from 2021-08-09 17-41-53](https://user-images.githubusercontent.com/63247726/128771677-bb2c29a7-9caf-4a78-b3a2-7c683578da00.png)

**Closed** 2021-08-17 07:30 UTC
Labels: bug
