### ISSUE TITLE
Physics raycast node doesn't return object name for new objects (regression?)

### ISSUE THREAD

**Issue by Bugsbane** [armory3d/armory#1185] opened 2019-02-20 19:12 UTC
**Expected result:**
When using the Armory [raycast example file](https://github.com/armory3d/armory_examples/blob/master/physics_raycast/raycast.blend), the name of the object the cone is pointing at is printed when left clicking the mouse.

**Actual result:**
The name prints if it is pointing at the cube in the file, or a duplicate of it, but returns a blank name if pointed at any new object. Changing the name of either doesn't change the result.

**Description:**
It looks like something has changed with Blender 2.8 object creation, which is stopping the Physics Raycast node from correctly getting the name of newly created objects.

For example, see the physics ray example at:
https://github.com/armory3d/armory_examples/blob/master/physics_raycast/raycast.blend

It still works fine, printing the cube name, as long as the cone is pointing at the cube in the scene. It also works if the cone is pointing at a duplicate (alt-d or shift-d) of the same cube.

If the cone points at any newly created object created though, the name comes out blank.

The Get Name node seems to be working properly though. If I attach it to the same objects with a Print node, it prints all object names properly.

Kubuntu 18.10
Blender 2.8
Armory 0.6 beta / 0.6 git - a6c954cda7ca429e3887069100e11ba5441b88c9

[raycast-with-dupes-and-new-cube.zip](https://github.com/armory3d/armory/files/2886097/raycast-with-dupes-and-new-cube.zip)

**Comment by luboslenco** [comment] 2019-02-21 07:47
The problem is that logic nodes from the `Physics` category only work for objects with rigid body attached. We need to figure a way to make it clearer.

**Comment by Bugsbane** [comment] 2019-02-21 14:51
Ah, makes sense. The funny thing is that is *does* detect if it's pointing at an object which doesn't have rigid body attached. It registers. It just returns blank as a name. What if the blank was just replaced by a string like "Not a rigid body." That should give people debugging their nodes a pretty clear indication...

**Comment by zicklag** [comment] 2019-02-22 18:08
It is actually just printing blank if it doesn't detect anything. It can't tell the difference between pointing at nothing and pointing at an object that isn't a Rigid Body.

**Comment by Bugsbane** [comment] 2019-02-24 00:16
When it points at a non-rigid body object, it causes the console output to scroll down. :)

**Comment by zicklag** [comment] 2019-02-24 00:29
Yes, but it does that when it is pointing at nothing as well, right?

**Comment by Bugsbane** [comment] 2019-02-27 16:27
> it does that when it is pointing at nothing as well, right?

I didn't think it did, but I went and tested and you're right.

**Comment by zicklag** [comment] 2019-03-08 19:17
Yeah, I'd close this, now.

**Closed** 2019-03-10 23:09 UTC
