### ISSUE TITLE
[Add-on Reloader] Some reference to the parser context isn't correctly updated when reloading

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2301] opened 2021-08-10 23:06 UTC
See the comments below

**Comment by QuantumCoderQC** [comment] 2021-08-10 23:56
Seems to be caused by this:
https://github.com/armory3d/armory/blob/master/blender/arm/material/cycles_nodes/nodes_texture.py#L118

The condition
 ```Python
 if state.context == ParserContext.OBJECT:
 ```
fails even if its an object. I printed out the two lines and this is what it returned:
```Python
print(state.contest) #ParserContext.OBJECT
print(ParserContext.OBJECT) #ParserContext.OBJECT

```

Not sure why this is though.

**Comment by knowledgenude** [comment] 2021-08-11 01:17
Maybe some typo with space after ​ParserContext.OBJECT​ somewhere? Seems to be the only thing that makes sense

**Comment by N8n5h** [comment] 2021-08-11 03:03
It seems the comparison between enum instances is failing because it may need to be explicitly defined, at least that's what worked for me https://stackoverflow.com/questions/39268052/how-to-compare-enums-in-python 
https://stackoverflow.com/a/66892683
```Python
def __eq__(self, other):
        if self.__class__ is other.__class__:
            return self == other
        try:
            return self.value == other.value
        except:
            pass
        try:
            if isinstance(other, numbers.Real):
                return self.value == other
            if isinstance(other, str):
                return self.name == other
        except:
            pass
        return NotImplemented
```
or changing the subclass type to IntEnum (which seems discouraged by one the anwers of the thread I linked).

**Comment by MoritzBrueckner** [comment] 2021-08-11 10:57
The issue seems to be a bit more fundamental then this check, the `ParserContext` class seems to be loaded twice into memory (with the same name but two versions). If I add a print statement to the body of the class (that is allowed in Python and runs when the class is loaded), it is executed twice.

When you add `print(id(state.context), id(ParserContext.OBJECT))` before L118 in nodes_texture.py, you get something like
```
2314372551200 2314373421760
```

Which means that both enum values are actually different objects in memory, I guess that the `==` operator defaults to `is` for enums unless we're using some workaround like @N8n5h posted.

**Comment by MoritzBrueckner** [comment] 2021-08-11 17:44
Fixed in https://github.com/armory3d/armory/pull/2302 for cases without a prior reload of the addon, should we keep this open for the case after reload and rename the issue? There is still a cause for this somewhere (some reference to the parser context isn't correctly updated when reloading).

**Comment by knowledgenude** [comment] 2021-08-11 18:14
@MoritzBrueckner , i changed the title so you can suggest another if this one isn't descriptive. Thanks as always!

**Closed** 2021-11-25 09:44 UTC
Labels: bug
