### ISSUE TITLE
Compile problem - files props_ui.py, utils.py

### ISSUE THREAD

**Issue by polomskya** [armory3d/armory#1769] opened 2020-07-13 10:51 UTC
Hello.
If I want to launch any projekt in Armory, it recall me this problem. Can you help me?

![image](https://user-images.githubusercontent.com/68221280/87296074-829ca100-c506-11ea-931c-fecb225a6476.png)

Blender: 2.8x
info: for first time its was works properly. But I had to do something wrong. Then I was try to remove a reinstall Armory, but with no positive effect.

**Comment by polomskya** [comment] 2020-07-13 11:50
Sorry guys, think I found the problem.  I saved my project to folder with special characters ( ! ). :D

**Comment by MoritzBrueckner** [comment] 2020-07-13 12:06
Hi, yes that is the cause of the bug but usually a warning is printed, not an error. It is already fixed in https://github.com/armory3d/armory/pull/1764, you should update to the latest Git version (`User Preferences > Addons > Armory > Update SDK`) and then it should work again - even with special characters. Thanks for reporting!

**Closed by MoritzBrueckner** 2020-07-13 12:06 UTC
Labels: bug
