### ISSUE TITLE
Reimplementing voxel gi

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2549] opened 2022-08-11 09:18 UTC
Hi, I'm trying the sdk with armory and iron checked out to 19.02, after a few modifications it runs with blender 2.93 but ... rendered frame is all black.
There are no errors, no warning.
With a default scene:
```
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/i20/Documents/armsdk//nodejs/node-linux64', '/home/i20/Documents/armsdk/Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_cube/debug', '--nohaxe', '--noproject']

```

**Comment by MoritzBrueckner** [comment] 2022-08-13 22:22
> I'm leaving this thread and am awaiting for answers on https://github.com/armory3d/armory/issues/2549

The microshadowing PR is indeed not the right place for discussion related to this issue :)

> I don't know what these columns ":" are used for in python3, I replaced them with an assign symbol "=" and it'd be running if not stuck on these same columns in a function declaration's arguments.

Those colons are used for type hints that specify what type a variable or parameter has. Python ignores the hints at runtime but they are valuable information for IDEs to show better warnings. Blender also (mis?-)uses the type hint syntax for property declarations. Since Blender 2.79 runs with older Python versions I guess you'd need to check out a very old state of the Armory SDK as well or you manually need to remove all type hints (still risking many other issues due to the much newer code).

> Ok my issue is with the function getFloat32 from Float32Arrays,
> It doesn't want to be called and states that it is not a function

Could it be https://github.com/armory3d/armory/issues/2376 by chance? If so, you can enable "Binary Scene Data" in the Armory exporter panel for now.

**Comment by e2002e** [comment] 2022-08-15 14:43
Yes it was that.
I've checked out to 19.02 and rebased to main, before realizing that I needed to rebase from main to 19.x.
Doesn't change much since the gi related changes are being scrolled through and I end up with a weird setup...
What about the raytracing render path ? Work seems done or at least almost done.

**Comment by e2002e** [comment] 2022-08-16 17:45
So when rebasing, HEAD is not the branch that we are coming from but the target... It made be go through a lot of pain, not kidding.
Voxel GI just works along the current 'main' branch. Needs also a change to iron because when testing for rp_voxelao, it should be rp_gi != "Off", so that the voxel related fonction get compiled.
I don't know if you'r going to merge that but it's ready as described.

**Comment by MoritzBrueckner** [comment] 2022-08-18 21:14
> What about the raytracing render path ? Work seems done or at least almost done.

I'm not sure about this, if I remember correctly it was never finished because of the state of Kha's g5 API. But probably only Lubos can answer this question.

> Something is annoying me, it's when I set physics type to "mesh" there is a massive lag

Can you reproduce it in newer versions of Armory? Then it's probably worth an issue. I also had massive physics-induced lags in your church scene from the translucency issue but I think they were caused by all the rigid body chairs.

**Comment by e2002e** [comment] 2022-08-19 09:15
>Can you reproduce it in newer versions of Armory? Then it's probably worth an issue. I also had massive physics-induced lags in >your church scene from the translucency issue but I think they were caused by all the rigid body chairs.

I just tried with another file and it must be a conflict between physics properties, no issues with another scene and a few rigibbodies with mesh shape.

**Comment by e2002e** [comment] 2022-08-22 17:00
@MoritzBrueckner Hi, I'm reporting I've tried many tweaks but lost tracks. I got neither AO nor GI with voxels when using a rebase ommiting the commits that drop voxelgi, I guess I'm at about nothing to get it to work though.

**Comment by e2002e** [comment] 2022-08-22 19:11
For voxel gi:
Objects that are hit by a direct lamp ray are lit, but if the 'env' parameter is at 0, there are no indirect light.
Which is a great thing to observe since it proves the lighting is made by voxels.
Any other
![NOVOXELS](https://user-images.githubusercontent.com/29781855/186000127-210ab353-3e29-47eb-a13f-bf084891e152.png)
 parameter has no effect for voxel GI, this is worrying.

![VOXELAO](https://user-images.githubusercontent.com/29781855/186000141-f29efcc2-4f8d-4ff2-8fcf-d9c29da0b4f6.png)
![VOXELGIENV1](https://user-images.githubusercontent.com/29781855/186000157-9306a908-9c5a-47d5-9147-f6736e49f4d2.png)

**Comment by e2002e** [comment] 2022-08-22 22:06
Other test:
No voxels
![NOVOXELS](https://user-images.githubusercontent.com/29781855/186026336-65fcaa68-2edf-4680-bbb2-e484eb16855b.png)
voxel ao
![VOXELAO](https://user-images.githubusercontent.com/29781855/186026355-f5e6a4cb-b97f-4593-bf76-796399930692.png)
voxelao plus voxel shadows
![VOXELAOShadows](https://user-images.githubusercontent.com/29781855/186026380-2921f94e-4d83-405b-964e-6d735d038e2d.png)
and the last, voxel gi:
![VOXELGIENV1](https://user-images.githubusercontent.com/29781855/186026487-2dcce77b-8e68-40d1-bf1b-9e4cc98cabcb.png)
There is a problem with the GI, it doesn't take anything else than environment contribution. And areas of objects that are not directly hit by lights are just tainted with the sky color, are they ?

I'm uploading so that you can take a look, especially in the render deferred file where things are put together.

**Comment by e2002e** [comment] 2022-08-23 19:11
There is a function used in make_renderpath.py that is not used anymore with voxel gi: "assets.add_shader_external". It is used for adding the voxel ligh pass itself and the voxel bounce, but had not effect.
I replaced the call with assets.add_shader_pass and created a .json file for the shaders.
Yet I'm stuck here because gl_GlobalInvocationID is not recognised by opengl. ANY CLUES ?

**Comment by e2002e** [comment] 2022-08-23 21:07
I renammed the shader into .com.glsl realizing that it is a compute shader.
Now I got armory trying to treat it but same error. Is there a way to make the gpu know that it's a compute shader.

**Comment by e2002e** [comment] 2022-08-25 19:52
In Inc.hx there is (version with GI) computeVoxels and:
```
kha.compute.Compute.setSampledCubeMap(voxel_te, rts.get("shadowMapCube").cubeMap);
```
And the engine reports:
```
trace: TypeError: Cannot read property 'image' of undefined
    at Function.computeVoxels (<anonymous>:1970:130)
 
```

**Comment by e2002e** [comment] 2022-08-29 10:08
@MoritzBrueckner I got an error `Trace: TypeError: Cannot read property 'setPipeline' of null̀` when calling drawMesh("voxel") line 586 in RenderPathDeferred.hx. This only happens when invoking the computeVoxels functions related to voxelgi.
I'm lost with the bindTarget mechanism, can you have a look at the files ?

**Comment by e2002e** [comment] 2022-08-29 15:41
@MoritzBrueckner I'm stuck, the voxel texture is not being updated. It's all black, and only direct light is shown, or contribution from the environment. I'm quite sure that either the voxel texture is not set before going through compute shaders or that it's not retrieved afterward.

**Comment by MoritzBrueckner** [comment] 2022-08-29 19:25
Hi, there is no need to ping me for every update, I will see it anyways but sometimes I might take a while to answer.

I can't tell you what's wrong from far away. I never spent much time with the voxel code, so I don't really know much about it. Have you tried setting the texture if you think it hasn't been set? Also, a graphics debugger like [RenderDoc](https://github.com/armory3d/armory/wiki/debug#renderdoc) will probably help you here.

In general, reimplementing voxel GI seems like a complicated undertaking. I don't know why Lubos removed this feature a long time ago (I guess it was to be replaced with something better), but implementing it (and making sure it's fast) is certainly not easy and that's likely one of the reasons why nobody has done it so far. I don't know about your background, but maybe some simpler issues are better suited for getting started with Armory development. I don't want to keep you away from this though – if you think you can do it then sure, go ahead!

**Comment by e2002e** [comment] 2022-08-29 22:16
> Hi, there is no need to ping me for every update, I will see it anyways but sometimes I might take a while to answer.
Copy that.
> I don't know why Lubos removed this feature a long time ago (I guess it was to be replaced with something better)
It's clear throughout the commit messages and comments that this had to be replaced with a raytracer.
> I don't know about your background, but maybe some simpler issues are better suited for getting started with Armory development.
I don't want to spend my time (which is all I have) on minor stuffs, I know this sound arrogant but truth is I need a carrot to advance. This module is already done and needs to be reimplemented for v21, tweaking code is a thing I have been used to when working on john the ripper. If I get to the end of that I will let you known.

**Comment by e2002e** [comment] 2022-09-01 23:25
By any chance, do you know how the shaders are put together or treated ? I got the voxels vert, geom and frag in the build/Shaders folder but I'm unsure about if their unused or are not compatible with the voxel compute shaders.

We got the voxel shaders themselves for the "cubes" say, and these are enough for voxel AO to trace cones, but with voxel gi there are compute shaders that are supposed to take part in the pipeline, when calling the compute voxels being / compute / end functions.
Not sure about what is really needed here, maybe the lattest working voxel gi didn't need the compute shaders.

**Comment by MoritzBrueckner** [comment] 2022-09-02 12:31
> By any chance, do you know how the shaders are put together or treated?

That's a pretty broad question, so please correct me if I'm answering the wrong question. Shaders are either referenced by materials, or by a .json file inside the folder of a shader pass (in case of non-material stuff to which Voxel GI belongs). [This](https://github.com/armory3d/armory/tree/main/Shaders/bloom_pass) for example is the folder used by the bloom pass (I'm just picking that randomly here).

Shaders passes then need to be loaded at runtime. For material shaders, this is automatically done for you, but for other shader passes that you manually invoke from the render path, you need to load them yourself (bloom example again):

https://github.com/armory3d/armory/blob/e59cbf3803bbe2c8dcd8ba17dbc58bde5edcd462/Sources/armory/renderpath/RenderPathDeferred.hx#L303-L306

Then you can draw the actual shaders as a full screen quad/triangle (not sure what's used in Armory):
https://github.com/armory3d/armory/blob/e59cbf3803bbe2c8dcd8ba17dbc58bde5edcd462/Sources/armory/renderpath/RenderPathDeferred.hx#L708-L710

For compute shaders the approach is a bit different, but keep in mind that there are targets that may not support compute shaders. As far as I know (I never really implemented anything with compute shaders in Armorys, but I've played around with them in the past), you use [`path.getComputeShader()`](https://github.com/armory3d/iron/blob/926d5956b3781e394dc18e1c147a10ce5cdb2f8b/Sources/iron/RenderPath.hx#L486-L488) to retrieve the shader object:

```haxe
// Load and set shader
final shader = path.getComputeShader("my_shader");
kha.compute.Compute.setShader(shader);

// Set parameters
// ...

// Invoke the compute shader
kha.compute.Compute.compute(x, y, z);
```

**Comment by e2002e** [comment] 2022-09-03 15:09
Doesn't seem to treat materials_voxel.vert/geom/frag while Voxel GI is active.
That is the point i'm missing: at which point are the shaders put together ?

**Comment by e2002e** [comment] 2022-09-03 20:45
Ich habe keine zit mehr fur werk das, aufviedhersehen Moritz

**Comment by e2002e** [comment] 2022-09-07 17:01
@MoritzBrueckner, I have a non found uniform, which I guess is important: LWVP lightWorldViewProjection, included from make_gi in make_voxel.py (verstion 19.02). I checked and other functions are using the same uniform in iron. Any idea ?

**Comment by e2002e** [comment] 2022-09-08 16:05
Hi, I'm sure now this is an issue with the textures,
In RenderPathDeferred.hx we create a render target named voxelsOpac and bind it to "voxels" for processing by the shaders,
The issue is that this image is not recognised: the engine goes "TypeError: Cannot read property 'image' of undefined" at each reference to voxelsOpac, there is not problem with the voxel image of voxelAO, I'm going to look into the InitGi function.

**Comment by e2002e** [comment] 2022-09-08 21:52
@MoritzBrueckner pinging here since I don't know if you get messages from closed issues.

**Comment by e2002e** [comment] 2022-09-09 22:42
when creating voxels texture, if name is "voxels" np. If name is something else, the render target is "not defined", texture is not the issue. I'm pushing changes and if you have time to get a look at that please do.

**Comment by MoritzBrueckner** [comment] 2022-09-11 16:26
Hi, yes I also get notified when issues are closed, but this is open again anyways :)

I'm afraid I can't really help you here, at least not with more information. The `TypeError: Cannot read property 'image' of undefined` (I guess it's the same issue as the undefined render target?) are caused by something in your Haxe code, make sure that the render targets are correctly created/initialized and that you do not confuse the order of arguments for the `path.bindTarget()` function.

**Comment by e2002e** [comment] 2022-09-11 18:27
Nei, the rendertarget is created in initGI in Inc.hx,
When invoking clearImage, it should not have needed to bind the target.
What I'm looking for now is something that would erase RenderTargets["voxelsOpac"], or prevent it to be created.

**Comment by e2002e** [comment] 2022-09-12 16:28
Kein gluck, ich verstehe nicht.
Ich habe eine spiel mit krieg fur den tagen.
Ich wurde arbeiten when ich can.

**Comment by e2002e** [comment] 2022-09-13 13:57
My main issue is about "Cannot read property 'image' of undefined" when calling rt.image.clearImage.
Do you think it's about rt or image not being defined ?
Really going to have to clean the hobs after that.

**Comment by e2002e** [comment] 2022-09-13 16:17
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENEXR_ILMIMF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /home/i20/Documents/upbge/intern/cycles/kernel/osl
    linked by target "cycles_scene" in directory /home/i20/Documents/upbge/intern/cycles/scene

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by MoritzBrueckner** [comment] 2022-09-14 22:52
Hi, sorry, I didn't see that you have pushed your changes already.

> My main issue is about "Cannot read property 'image' of undefined" when calling rt.image.clearImage.
> Do you think it's about rt or image not being defined ?

The error message says that it can't read "image _of_ undefined", so it's `rt` that is null here. If you are in doubt, just print the value of `rt` and see yourself. Also, it is often useful to look into the generated .js code to see where exactly an error happens.

I don't have time to debug your code (that's something you need to do yourself), but to me it looks like you correctly initialize the rendertargets with `Inc.initGI("voxelsOpac")` for example. Perhaps something is wrong with the `#ifs` etc.? Have you added a print statement to check whether the initialization code is actually reached? If you export the Armory project and setup your VSCode accordingly, you can even use it's debugger to get more insight about variable values at runtime, such as the map of render targets :)

**Comment by e2002e** [comment] 2022-09-15 12:55
Hi, thanks for the answer, I've been also busy with applying a patch for ssgi into upbge, you can start worry about them ;)
Issue is I did not find any way to print out data with haxe. Common issue as I saw online, it asks the code to run with a specific platform but it do not understand the compilation mechanism of haxe. You propose a lot of languages when exporting but krom or browser only for runtime, it krom a compiler for haxe ?
What I was able to discover through my investigations is that rt["voxelsOpac"] contains <Null>RenderTarget, so this is a pointer to a target which is not declared.
I'm annoyed here because there is not any difference between the way "voxelsOpac" and "voxels" are declared, but for the image format, which is unimportant for this bug.

**Comment by e2002e** [comment] 2022-09-18 09:48
Hi, I did not read the initGI function properly; it checks for voxelsCreated and if true returns before doing anything else, and since this variable is set to true inside initGI, it can only be called once.
Got rid of that, images are well created, yet now the engine asks for biasLightWorldViewProjectionMatrixSun, present in iron.Uniforms.
I guess once this data is present the voxel light will appear..
Gut Sonnertag.

**Comment by e2002e** [comment] 2022-09-18 18:15
I'm sure I saw a function that reviews the shaders and adds the uniforms to context afterward, when in voxel gi / ao, no uniform from iron can be added, only those from armory.

**Comment by e2002e** [comment] 2022-09-19 00:19
It seems that  the voxels are working, but only when volume light is activated, and only inside the light ray.
![voxelsGI insideVolume](https://user-images.githubusercontent.com/29781855/190934197-d801dc2b-657a-44e2-a85e-417184a3c58a.png)

![voxelsGI outsideVolume](https://user-images.githubusercontent.com/29781855/190934202-9689b86f-2771-4d51-b862-4db7bf980685.png)

**Comment by e2002e** [comment] 2022-09-19 11:49
I set ssgi to ssao and unlit faces are appearing, 
issue is that it's like in the first place, there is no lighting except from the environment.
![voxelenv0](https://user-images.githubusercontent.com/29781855/191010745-fd21d9aa-5ad4-4613-98d9-25773fba28a5.png)
![voxelEn1](https://user-images.githubusercontent.com/29781855/191010764-c350a0fe-3d25-469d-afc8-e28fd4230aba.png)

**Comment by MoritzBrueckner** [comment] 2022-09-20 21:18
That's great news :)

> I'm sure I saw a function that reviews the shaders and adds the uniforms to context afterward

Perhaps you are referring to [`make_datas.parse_shader()`](https://github.com/armory3d/armory/blob/d1164adcb0c676c8f7288003e4da066e08356af8/blender/arm/lib/make_datas.py#L82)? I'm not sure though if it's also used for the standard shaders or just for user shaders, so you need to check this. Also note that it's in Python, so it's called at export and not at runtime.

> when in voxel gi / ao, no uniform from iron can be added, only those from armory.

Did you add the uniforms to the .json file (and are all defines correctly declared)?

**Comment by e2002e** [comment] 2022-09-20 23:05
Hi, i'll check the parse_shader now,
> Did you add the uniforms to the .json file (and are all defines correctly declared)?
That is the thing I don't get, the context of the shader is written somewhere I don't know.

**Comment by e2002e** [comment] 2022-09-22 18:34
I'm closing this as it would take ages for some random saviour to read through the issue, unmöglish fur mich. If you got time for this, the fork is rebased from 18.09a, this was really all the tedious work for me. Viel gluck

**Comment by e2002e** [comment] 2022-09-25 12:10
Can you help me here ?

**Comment by QuantumCoderQC** [comment] 2022-09-25 13:36
Hi, I would like to help you, but I am not fully aware of the current situation that you are in. 

It would be great if you could please explain it in as much details as possible. So we dont assume something and/ or suggest things you might have already tried. I know I can follow the tread above, but it still does not quite paint the full picture.

**Comment by e2002e** [comment] 2022-09-25 13:54
Hi Quantum, the voxels GI works as so:
First it creates the voxels through the voxels users shaders created in make_voxels.py,
Then the compute shaders deals with light bounces and subdivisions of voxels (which is step 2 in the voxel workflow if I remember the articles). These are called in RenderPathDeferred.hx and defined in Inc.hx.
The last step is cone tracing, to deal with datas created from the camera point of view, it's in conetrace.gsl in the Shaders folder.

My guess is that the voxels 3d sampler is empty, so you can ignore the conetrace procedure.
This sampler is used in the compute shader, my guess is that it fails in the first place in create_voxels.py.
I haven't read through these functions, merely checked everything was compiling and in order when rebasing from 18.09a.
So at that point, we get only the light from the environment when activating voxels gi, i.e indirect light is black.

**Comment by e2002e** [comment] 2022-09-25 15:17
![Screenshot_20220925_171106](https://user-images.githubusercontent.com/29781855/192150861-e2a92cd5-5c13-4fff-9f19-48d9602f5e81.png)
This was not possible to verify with cubes, but as you can see here there are variations on the faces not directly hit by light.
Only thing that make
![Screenshot_20220925_171510](https://user-images.githubusercontent.com/29781855/192151125-3a7e654c-8a9f-429b-a925-4cd790475eaf.png)
s me doubt is that with no environment light contribution set for the voxels, shadows are pitch black.

**Comment by e2002e** [comment] 2022-09-25 19:15
https://youtu.be/9amC1WfdNsY
I've recorded this to confirm that voxel gi works (or not), this is used with RTAO and I'm playing with the limit of the voxels to show the difference between only rtao and both. This should be a success yet I'm waiting for someone to acknowledge.

**Comment by rpaladin** [comment] 2022-09-25 20:20
Hi @e2002e, a friendly observation, people following this repository receive notifications every time you close or re-open one of your created issues or PRs: for instance in this very issue you've closed/re-opened **_three_** times already. In the past, you'd done this repeatedly, and honestly, it's not very nice... I can only imagine how many extra notifications Lubos is getting, and he is quite busy (as are most of the repository followers).

Posting (and perhaps even user mentioning once in a while) is fine I think, but I'd suggest leaving the closing/re-opening of issues/PRs by repository maintainers such as Lubos or MoritzBrueckner, that way, closing/re-opening is kept at a minimal and less spammy.

Again, this is just a friendly suggestion, hope the best of things, cheers.

**Comment by e2002e** [comment] 2022-09-25 20:57
Sorry no mean to piss you off I just clicked the close button inadvertantly

**Comment by rpaladin** [comment] 2022-09-25 22:49
No problem! I myself have accidentally closed two PRs quite recently, unfortunately.

**Comment by e2002e** [comment] 2022-09-26 11:42
Doesn't work, I'm sure. Occlusion, diffuse and glossy parameters have no impact on the scene.

**Comment by e2002e** [comment] 2022-09-26 22:10
make_voxel doesn't take rgba32 nor R32 images, only r8,
gi with this does a redish render.
![Screenshot_20220927_001007](https://user-images.githubusercontent.com/29781855/192389610-d8fcc0ec-b899-4f37-a8b8-a6076322a7d8.png)

**Comment by e2002e** [comment] 2022-09-27 22:10
I'm wrapping up the situation for who can help.
- images are created in Inc.hx. They need to be R32.
- the voxels shaders created in blender/arm/make_voxels.py are correctly creating the voxels.
At that point, we get a voxel light but only with R8 image (hence the red tone) and also provided we skip the next part and tweak the bindings to have "voxels" and not "voxelsOpac" used in rendering.
- the next part, which is failing, is to retrieve the content of the voxelOpac and do some magic stuff that only @luboslenco knows, then write the result on voxels, and the functions in conetrace will do the rest.

**Comment by e2002e** [comment] 2022-09-29 18:57
I took the files from 18.01, binding the shadowmap before the voxel creation, and not using the compute shaders.
With rgba64, it just works !
![Screenshot_20220929_203414](https://user-images.githubusercontent.com/29781855/193118650-f3ef524e-1fdc-43fa-8157-454b6f33d828.png)

There is a strange circle appearing, probably because of the conetracing. For now, I'll try to make use of the computer shaders again.

**Comment by e2002e** [comment] 2022-09-30 10:55
![Screenshot_20220930_125227](https://user-images.githubusercontent.com/29781855/193254998-1d42627c-eb58-4de2-beb1-d9ba38e24e69.png)
Emission working.
revoxelize and dynamic camera giving no artifacts.
Temporal filter has a shutter when used with dynamic camera.
I'm going to work on refraction, which is not working at all.

**Comment by e2002e** [comment] 2022-09-30 18:06
Here is a screenshot of an interior scene with voxel GI an SSAO.
![Screenshot_20220930_200446](https://user-images.githubusercontent.com/29781855/193330468-9aa00faa-e499-4ea9-a013-c32da99611bc.png)
The solution to light areas passing through walls is a combination of enough subdivision and ambient occlusion.

**Comment by e2002e** [comment] 2022-10-02 02:33
Okay this is all setup, I'm going to be ready for the pull request but when I do all files are marqued as changed.
When I cloned my fork, I copied another folder on to of it, and lost the git files, had to reinit the folder, help with that would be great.

**Closed** 2022-10-02 13:04 UTC
Labels: feature request
