### ISSUE TITLE
combine vector connected to mapping node

### ISSUE THREAD

**Issue by Redfill** [armory3d/armory#1515] opened 2019-12-15 19:22 UTC
**Description**
when connecting a vector to the scale input of the mapping node, it doesn't have any influence

**To Reproduce**
add a mapping node between your uv and your texture, add a "combine vector" and connect it to the scale input of the mapping node, set random numbers and run.

**Expected behavior**
that the scaling is done properly according to the combine vector

**System**
Blender: 2.81
Armory: latest
OS: ubuntu
Graphics card: gtx 950

[VectorConnectedToMapping.zip](https://github.com/armory3d/armory/files/3965339/VectorConnectedToMapping.zip)

**Comment by N8n5h** [comment] 2019-12-15 19:52
Not a bug, support for taking the input of the mapping node has yet to be implemented, currently it uses the default value.

**Comment by Redfill** [comment] 2019-12-15 19:55
then is there another way i can change the values during gameplay?

**Comment by N8n5h** [comment] 2019-12-15 19:59
By using material parameters? Not sure if right now it's possible. 

Taking the values for the input sockets has to be done here 
https://github.com/armory3d/armory/blob/1f8aed23bf29e56047081416c0942a0cd4bc00fe/blender/arm/material/cycles.py#L898

**Comment by MoritzBrueckner** [comment] 2020-04-11 15:21
Should be fixed in https://github.com/armory3d/armory/pull/1649, thanks for reporting :)

**Closed** 2020-04-12 09:34 UTC
Labels: bug
