### ISSUE TITLE
issue in spawn

### ISSUE THREAD

**Issue by mhreez** [armory3d/armory#1662] opened 2020-04-15 16:11 UTC
Thank you for contributing to Armory!

**Description**
Issue description.
when I want make spown from object and this object contain groub .thw spown after 4 time make the game is very slow if I add another spown the game stop 

if you open the file
**F** to make floor is ready and **Left mouse** to make spown

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
What you expected to happen.
I expect beause of the group

**System**
Blender: 2.82
Armory: 2020.04.02
OS:
Graphics card: gtx 1050 

**Test File**
*(drag & drop the zipped
[untitled.zip](https://github.com/armory3d/armory/files/4482364/untitled.zip)
 .blend file here)*

**Comment by QuantumCoderQC** [comment] 2020-04-15 16:34
Hi @mhreez 

This is not a bug. The issue you are facing is because of misuse of node traits. That is, the spawn object node is applied to the object that is to be spawned. This will lead to an exponential increase in the objects spawned, slowing down the game. You may check the debug console for the number of objects spawned for each "click".

To solve the issue:
1. Remove the trait "Floor building" from the object "floor for respawn".
2. Add the trait "Floor building" to the object "Plane".

I hope this solves the issue.

Best Regards,
QC

**Comment by mhreez** [comment] 2020-04-15 16:40
thank you so much

**Comment by MoritzBrueckner** [comment] 2020-07-03 14:36
Closing this issue as it is resolved now

**Closed by MoritzBrueckner** 2020-07-03 14:36 UTC
Labels: bug
