### ISSUE TITLE
armory and blender 2.83 test not interactive

### ISSUE THREAD

**Issue by zartan9** [armory3d/armory#2040] opened 2020-12-02 06:28 UTC
hi is there a step im missing? nodes are set up to rotate but f5 there is no interaction? thanks.
![blendernodesbutnotrunninghmm](https://user-images.githubusercontent.com/74879950/100836634-9d33d000-343d-11eb-8bd9-ea54b82cc97e.png)

**Comment by e1e5en-gd** [comment] 2020-12-02 07:10
I don't quite understand what the problem is:
- for rotation, use the `Rotate Object` node from the `Transform `section;
- `Torque` nodes from the `Physics` section are used to rotate a physical body according to physical laws.
Is your node anchored to an object? Or if you want to rotate another object, but the script is attached to another object, then you need to specify it.

**Comment by MoritzBrueckner** [comment] 2020-12-02 07:50
Also, make sure that your trait is attached to an object or scene in the properties panel.

**Comment by zartan9** [comment] 2020-12-02 17:50
thank you for quick replies. Yes, it was the missing trait to get it working when f5. Im new to this im trying to have 2 physical objects when collide switch scenes... Not to reinvent wheel is there a link to this in node method (I didnt find one yet...) thanks for helping a noobie!!

**Comment by e1e5en-gd** [comment] 2020-12-02 17:58
For collision information, use the `Contact` nodes in the `Physics` section.
To receive a collision **event**, you must use the `On Contact` node, specifying the objects for collision.

**Comment by zartan9** [comment] 2020-12-02 19:13
ok i will look further into it. right now im trying to get the mesh to be dynamic trying to figure out if i do this thru blender or armory...

**Comment by MoritzBrueckner** [comment] 2020-12-02 19:41
If you are looking for shapekeys, they aren't supported in Armory yet, but there are other ways to manipulate meshes (bone animations, scripting, etc.)

I'm closing this issue as it is resolved now, please use the forum (https://forums.armory3d.org/) if you have further questions.

**Closed by MoritzBrueckner** 2020-12-02 19:41 UTC

**Comment by zartan9** [comment] 2020-12-03 04:59
thank you!!!
