### ISSUE TITLE
Edit script not opening vs code

### ISSUE THREAD

**Issue by zeeshan595** [armory3d/armory#1399] opened 2019-09-23 05:59 UTC
Thank you for contributing to Armory!

**Description**
I setup the vs code editor but for some reason when i click edit script in Armory Traits it opens the script in firefox
![Screenshot from 2019-09-23 06-56-34](https://user-images.githubusercontent.com/6005448/65404117-262d9100-ddcf-11e9-8465-28d271ff5b53.png)

**To Reproduce**
Create a script and then click Edit Script

**Expected behavior**
What you expected to happen.

**System**
Blender: 2.80 (sub 75)
Armory: 2019.9.0
OS: Manjaro Gnome
Graphics card: AMD Vega 64

**Comment by MoritzBrueckner** [comment] 2019-09-23 10:58
This is most likely fixed in #1381. It was caused by a call to "file://[filepath]"

**Closed** 2019-09-25 21:19 UTC
Labels: bug
