### ISSUE TITLE
(Realtime postprocess + Compositor) PPComp warnings

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2052] opened 2020-12-11 21:13 UTC
this three.js webgl2 example here is working fine on iOS 14.2 : 
https://threejs.org/examples/?q=webgl2#webgl2_volume_instancing
but exporting to html5/webgl2 (or webgl1 with legacy shaders) with Armory3D you will get a black screen on iOS 14.2.
On iOS 13.3.1 everything works fine.

I also get the below errors in the web dev console now (not sure if related to this issue) : 
```
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp3 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp5 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp6 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp7 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp8 not found. (kha.js, line 1)
[Error] WebGL: INVALID_ENUM: texParameter: invalid parameter name
	texParameteri
	setTextureCompareMode (kha.js:1:944491)
	(anonymous function) (kha.js:1:385507)
	(anonymous function) (kha.js:1:382557)
	render (kha.js:1:352629)
	submitDraw (kha.js:1:223761)
	drawMeshes (kha.js:1:222697)
	(anonymous function) (kha.js:1:59468)
	(anonymous function) (kha.js:1:60281)
	renderFrame (kha.js:1:219169)
	renderFrame (kha.js:1:321235)
	renderFrame (kha.js:1:101139)
	(anonymous function) (kha.js:1:73571)
	(anonymous function) (kha.js:1:520512)
	animate (kha.js:1:530955)
```

**Comment by MoritzBrueckner** [comment] 2020-12-12 14:45
Just a guess, but I think there might be a typo here:

https://github.com/Kode/Kha/blob/b4fb18402b04675146b1d0770d6cce4f30b36de6/Backends/HTML5/kha/js/graphics4/Graphics.hx#L445

Instead of `GL_COMPARE_REF_TO_TEXTURE` the parameter should probably be called `GL.COMPARE_REF_TO_TEXTURE` according to the [webgl documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texParameter), also in the [Haxe js API it seems that this parameter is only available on webgl2](https://api.haxe.org/js/html/webgl/WebGL2RenderingContext.html#COMPARE_REF_TO_TEXTURE) and [not on webgl1](https://api.haxe.org/js/html/webgl/RenderingContext.html) which is imported in the file linked above.

@RobDangerous Maybe you can help us here? Is this a Kha issue?

**Comment by RobDangerous** [comment] 2020-12-15 01:25
Hey, @onelsonic just reminded me that I forgot to comment here by closing https://github.com/Kode/Kha/issues/1274
The constants were added manually because they didn't yet exist in the Haxe API. They are on the top of the file, should be fine that way. The warnings listed here also look very much like a very different problem. Can't test iOS 14 things myself yet though and off-by-default browser features are not a priority.

**Comment by onelsonic** [comment] 2020-12-15 22:07
thanks @RobDangerou. I closed the duplicated issue in the Kha repo for clarity.
After further investigating it,
this below:
```
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp3 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp5 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp6 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp7 not found. (kha.js, line 1)
[Log] kha/graphics4/PipelineState.hx:96: Warning: Uniform PPComp8 not found. (kha.js, line 1)
```
appears with the recent modifications in the armory UI when using the combination of features below you will get these errors and it affects [html5] exports on ALL devices not only iOS:
- [X] Realtime postprocess (Armory Render Path > Renderer > Realtime postprocess)
- [X] Compositor (Armory Render Path > Compositor)
---------------
As for the iOS black screen problem against all odds Apple decided to update its Safari webGL1/2 implementations with multiple updates since July so better be prepared there as additional webGL openGL ES extensions have been added to Safari on iOS14. Beside Threejs and Babylonjs are both supporting it now.

I just tried with the iOS14.3 update and same problem black screen on iOS.
After multiple tests the back screen on iOS occurs only if the the above settings are used.
So the Compositor effects implementation with "**Tonemap**" and "**LUT texture**" does not work on safari iOS.

It can be a problem with textures as @MoritzBrueckner has pointed?

I tried replacing `GL_COMPARE_REF_TO_TEXTURE` by `GL.COMPARE_REF_TO_TEXTURE` and I am not even sure if we can have variables with a point "." as a special characters in Haxe? It returns some compilations errors when replacing it.
@RobDangerous probably know better on this.

And not sure if it might be better to stick with the official API documentation if this can cause errors?
I found this webgl2.0 doc below on the khronos website and it is last updated in march this year:
https://www.khronos.org/registry/webgl/specs/latest/2.0/

renaming this issue for better follow up : "[html5] all devices (Realtime postprocess + Compositor) PPComp errors + iOS Compositor black screen"

**Comment by MoritzBrueckner** [comment] 2020-12-15 22:39
> It can be a problem with textures as @MoritzBrueckner has pointed?

Robert is right, I didn't see that the constants were defined at the top of the file, so what I wrote is not the problem here.

> I am not even sure if we can have variables with a point "." as a special characters in Haxe?

The point is a part of the Haxe syntax and not of the variable itself (= take the attribute/variable that's called `COMPARE_REF_TO_TEXTURE` from the class called `GL`), but as I pointed out it is not available in the Haxe webgl1 API which is probably the reason to use a custom constant (as Rob wrote).

Also, those PPComp messages are just warnings that some values couldn't be passed to a shader, they might be completely unrelated. I'm not sure if I understood you correctly, does the blackscreen also only happen when those warnings show up?

**Comment by onelsonic** [comment] 2020-12-16 21:57
the warnings are coming I think from the **compositor_pass** fragment shader and it is where we can find the 
`PPCompXX` uniforms :
https://github.com/armory3d/armory/blob/4038a67385d3cc0d92d1455f991820c62129eee3/Shaders/compositor_pass/compositor_pass.frag.glsl#L57

and they originated from this commit here : the merger of the superb lightmapper by @Naxela  :
https://github.com/armory3d/armory/commit/60f72e7e0ed93991762920aea0e5b8b670079f7f

it remained unnoticed until the recent changes to the Realtime postprocess option, as it is now working as it is supposed to.
- [X] Realtime postprocess (Armory Render Path > Renderer > Realtime postprocess)

Then about black screen on safari correcting my previous comment, as following more tests
it seems it is coming from activating the HDR option
- [X] HDR (Armory Render Path > Renderer > HDR)
What happen when you do activate `HDR` I am not sure.... any inputs on this is welcome.
The safari Dev console doesn't output anything else than the warnings above.
My guess is that some shader when using HDR need to be made compatible with OpenGL ES 310 in its syntax.
But not sure which one.

**Comment by Naxela** [comment] 2020-12-17 07:50
Hi,

Not sure why it's only on some devices that it doesn't work, but also that some of the Postprocess uniforms (PPCompX) isn't passed. In either way they shouldn't be a problem/not show up if **Realtime Postprocess** isn't turned on, since they should be omitted during preprocessing: https://github.com/armory3d/armory/blob/4038a67385d3cc0d92d1455f991820c62129eee3/Shaders/compositor_pass/compositor_pass.json#L112 with the _CPostprocess directive - Which again is added here, if the **Realtime Postprocess** option is toggled: https://github.com/armory3d/armory/blob/4038a67385d3cc0d92d1455f991820c62129eee3/blender/arm/make_renderpath.py#L203

I can't really figure out what 3,5,6,7,8 have in common since they're the ones throwing warnings. I'm not sure if they're the cause of the black screen, but would be nice to suppress those warnings anyway.

As for the HDR, are there any differences if you choose forward or deferred rendering?

**Comment by onelsonic** [comment] 2020-12-20 22:04
thanks @Naxela
this commit here should fix the warnings if using a custom render path : https://github.com/armory3d/driver_celshade/pull/10/commits/34e1a007b93f6c23c221bafee6e5f64fe8d8cc4e
The _CPostprocess directive should be correctly declared for all render paths existing in a Blender file.
Then if the warnings still persist, the only option I found was to recreate the Blender file from scratch and only have one render path setup. 
If you need another render path use another blender file.

Anyone have more info about what does the HDR option?

**Closed** 2020-12-23 20:41 UTC
Labels: bug
