### ISSUE TITLE
Trace message missing the last character

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#869] opened 2018-09-09 02:06 UTC
As captioned. 
For example, the last "T" is missing here:
![image](https://user-images.githubusercontent.com/17811339/45260349-03287d00-b418-11e8-9df3-ae8013e2f0b8.png)

/Milo

**Comment by luboslenco** [comment] 2018-09-09 17:11
Hm unable to reproduce here, does it happen in all projects for you?

**Comment by MiloHX** [comment] 2018-09-09 22:37
Hi @luboslenco , yes, all project have this issue. I created a testing file below (press space to print message):
[Print_Message.zip](https://github.com/armory3d/armory/files/2364725/Print_Message.zip)

![image](https://user-images.githubusercontent.com/17811339/45269632-dc278500-b4c3-11e8-841c-6d7bb289f0d9.png)

**Comment by MiloHX** [comment] 2018-09-12 13:58
Ah I forget to include the script in the zip file, attachment has been updated!

**Comment by luboslenco** [comment] 2018-09-21 19:29
Fixed in Armory 0.5a build.

**Closed by luboslenco** 2018-09-21 19:29 UTC
