### ISSUE TITLE
Logic Node - Set Trait Paused problem

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2117] opened 2021-02-27 11:47 UTC
Thank you for contributing to Armory!

**Description**
Logic Node - Set Trait Paused is not working properly

**To Reproduce**
![image](https://user-images.githubusercontent.com/39986875/109386238-a972e080-78f9-11eb-9549-ec62f7190faf.png)

**Expected behavior**
Rotate Trait should pause and unpause

**System**
Blender: 2.83.12
Armory: 2021.2
OS: Windows 10
Graphics card: Raden RX 580 4GB

**Test File**
[PauseTrait.zip](https://github.com/armory3d/armory/files/6054315/PauseTrait.zip)

**Comment by MoritzBrueckner** [comment] 2021-02-27 15:04
This is probably a duplicate of https://github.com/armory3d/armory/issues/1996 so I will close this issue. It seems that setting the paused state of a trait somehow triggers the mouse output twice which pauses and directly unpauses the trait...

**Closed by MoritzBrueckner** 2021-02-27 15:04 UTC
Labels: bug
