### ISSUE TITLE
game template "third_person_terrain" error

### ISSUE THREAD

**Issue by wahono77** [armory3d/armory#1943] opened 2020-10-21 06:23 UTC
**Description**
I just try game template "third_person_terrain". When I play in Krom, all is OK.
But when I play in browser,  all terrain in invisible and In inspect browser I got error:

kha.js:2760 Uncaught TypeError: Cannot read property 'b' of null
    at iron_data_TerrainStream.onReady (kha.js:2760)
    at iron_data_TerrainStream.loaded (kha.js:10983)
    at kha.js:10943
    at kha_Assets.loadImageFromPath.fileName (kha.js:9522)
    at HTMLImageElement.img.onload (kha.js:25370)

**System**
Blender: 2.90
Armory: Latest from Github
OS: WIndow 10
Graphics card: NVidia GeForce 940 MX

**Comment by wahono77** [comment] 2020-10-21 06:25
In kha.js line 2754, tex.getPixels result is null

var p = tex.getPixels();

**Comment by e1e5en-gd** [comment] 2020-10-21 10:01
For Armory to work correctly, you need Blender 2.83 (https://github.com/armory3d/armory/wiki/setup). Try on the specified version

**Comment by wahono77** [comment] 2020-10-21 17:36
> For Armory to work correctly, you need Blender 2.83 (https://github.com/armory3d/armory/wiki/setup). Try on the specified version
> P.S. The engine also develops and templates, examples may no longer be relevant

I just try using Blender 2.83 LTS, but the error still exist. Maybe this is a bug?

**Comment by MoritzBrueckner** [comment] 2020-10-21 18:09
Seems to be a duplicate of https://github.com/armory3d/armory/issues/1385 which looks like a Kha issue.

I'm not sure if this is a limitation of webgl ([documentation of `readPixels()`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels)), at least it looks as if it requires a workaround to implement the missing functionality in Kha for html5: https://stackoverflow.com/a/18804153/9985959. Maybe we should open an issue on the Kha repository to get it fixed.

**Comment by tong** [comment] 2021-07-23 13:47
Not related to the discussed above, but related to this issue:
For me terrain export fails on every target:

```
Exporting Scene
Python: Traceback (most recent call last):
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/props_ui.py", line 1039, in execute
    make.play()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/make.py", line 528, in play
    build(target=runtime_to_target(), is_play=True)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/make.py", line 416, in build
    export_data(fp, sdk_path)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/make.py", line 153, in export_data
    ArmoryExporter.export_scene(bpy.context, asset_path, scene=scene, depsgraph=depsgraph)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/exporter.py", line 155, in export_scene
    cls(context, filepath, scene, depsgraph).execute()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/exporter.py", line 2157, in execute
    self.export_materials()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/exporter.py", line 1836, in export_materials
    sd, rpasses = make_material.parse(material, o, mat_users, mat_armusers)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/make.py", line 45, in parse
    rpasses, shader_data, shader_data_name, bind_constants, bind_textures = make_shader.build(material, mat_users, mat_armusers)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/make_shader.py", line 74, in build
    con = make_mesh.make(rp, rpasses)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/make_mesh.py", line 62, in make
    make_deferred(con_mesh, rpasses)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/make_mesh.py", line 174, in make_deferred
    make_base(con_mesh, parse_opacity=parse_opacity)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/make_mesh.py", line 124, in make_base
    cycles.parse(mat_state.nodes, con_mesh, vert, frag, geom, tesc, tese, parse_opacity=parse_opacity)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 62, in parse
    parse_material_output(output_node, custom_particle_node)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 123, in parse_material_output
    out_disp = parse_displacement_input(node.inputs[2])
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 255, in parse_displacement_input
    return parse_vector_input(inp)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 267, in parse_vector_input
    res_var = write_result(link)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 519, in write_result
    res = parse_vector(link.from_node, link.from_socket)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 340, in parse_vector
    return node_parser_funcs[node.type](node, socket, state)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles_nodes/nodes_vector.py", line 140, in parse_displacement
    height = c.parse_value_input(node.inputs[0])
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 389, in parse_value_input
    res_var = write_result(link)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 519, in write_result
    res = parse_vector(link.from_node, link.from_socket)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles.py", line 340, in parse_vector
    return node_parser_funcs[node.type](node, socket, state)
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/material/cycles_nodes/nodes_texture.py", line 123, in parse_tex_image
    if tex['file'] is not None:
TypeError: 'NoneType' object is not subscriptable
```
It seems to work for krom if i change https://github.com/armory3d/armory/blob/97cc737aff8f0aa2914499cfbd482200d0a8389a/blender/arm/material/cycles_nodes/nodes_texture.py#L123
to
```py
if tex is not None and tex['file'] is not None:
```
But i've no idea what i am doing here.

**Comment by QuantumCoderQC** [comment] 2021-07-24 20:08
@tong Thanks for he report. This is related to a commit [here](https://github.com/armory3d/armory/commit/340f7e8af4a261ad72bc78b5e69d30fa919b1c8a#diff-17ef8fe32624d06dbcfbc4cc67374fe8e6fd97e8976cbcac04068b99e3d7fcca)

Will fix it soon!

**Closed** 2021-07-30 06:25 UTC
Labels: bug, kha

**Comment by QuantumCoderQC** [comment] 2021-07-30 19:35
Please re-open this issue as this not yet fully solved. The Krom side of things have been solved, but the original HTML5 issue still remains.

**Comment by MoritzBrueckner** [comment] 2021-07-30 21:43
Isn't this a duplicate of https://github.com/armory3d/armory/issues/1385 after all?
