### ISSUE TITLE
Is the flash past due to a memory graphics card?

### ISSUE THREAD

**Issue by chuiliuyiyi** [armory3d/armory#2832] opened 2023-03-23 07:34 UTC
window10
blender3.3.0
armory2303
No graphics card
armory player flash across，Is this the reason for not having a graphics card？

**Comment by chuiliuyiyi** [comment] 2023-03-23 22:52
No errors, one warning。
D:\ArmorySDK\armsdk/nodejs/node.exe D:\ArmorySDK\armsdk/Kha/make krom --ffmpeg D:\Program Files\python3.8.3\Scripts\ffmpeg.EXE -g direct3d11 --shaderversion 330 --parallelAssetConversion 4 --to build_untitled/debug --quiet
Finished in 22.505s
D:\ArmorySDK\armsdk/Krom/Krom.exe E:\aaa\build_untitled/debug/krom E:\aaa\build_untitled/debug/krom-resources --consolepid 5988
WARNING: Player exited code 2147483651

**Comment by chuiliuyiyi** [comment] 2023-03-23 22:53
When I compiled with vsc++, I found an exception breakpoint. Is it related to this.

**Comment by rpaladin** [comment] 2023-03-23 23:48
> WARNING: Player exited code 2147483651

This crash code was discussed at the Armory Discord a while back:

![image](https://user-images.githubusercontent.com/69180012/227388759-be2029dd-12d3-451d-9aaf-0544339ec1d5.png)

Here are the few solutions provided by @ QuantumCoderQC

![image](https://user-images.githubusercontent.com/69180012/227388807-951b5738-b461-4f2b-ab2a-75bac0104cea.png)

**Comment by chuiliuyiyi** [comment] 2023-03-23 23:51
Can you give me a link? I don't understand English and need a translation

**Comment by rpaladin** [comment] 2023-03-24 00:22
Could you please provide a blend that can reproduce the issue.

**Comment by chuiliuyiyi** [comment] 2023-03-24 00:25
It includes blender, krom windows, and windows hl build

**Comment by rpaladin** [comment] 2023-03-24 00:31
Your blend works fine for me in Armory (with and without cache). Your `Windows (Krom)` build works fine for me too. I personally can't test `Windows (C)` due to personal issues unfortunately, but others should be able to.

Can you please share the two crashlogs I mentioned in my last post above if you have them? Thanks!

**Comment by chuiliuyiyi** [comment] 2023-03-24 00:34
Yeah
[kinc.zip](https://github.com/armory3d/armory/files/11057436/kinc.zip)
No files stderr.txt

**Comment by MoritzBrueckner** [comment] 2023-03-31 23:47
Hi, is the flashing directly related to the crash (that is, the window opens on your screen and immediately closes)? Or are these two different issues (some flickering in the rendering for example and Krom crashes)? What exactly do you mean with "flash"?

> When I compiled with vsc++, I found an exception breakpoint. Is it related to this.

Is this the same issue as https://github.com/armory3d/armory/issues/2831?

**Comment by chuiliuyiyi** [comment] 2023-04-01 00:23
flash mean After clicking play, the window will appear and quickly close。
Associated with it #2831。
In short, it cannot be compiled or played, it can only be run in a web browser

**Comment by chuiliuyiyi** [comment] 2023-04-01 03:50
![image](https://user-images.githubusercontent.com/75259241/229264310-65f41efb-dad5-48a6-af80-a134c09c39f9.png)
I used vsc++2022 and still reported an error

**Comment by MoritzBrueckner** [comment] 2023-04-06 23:47
Sorry for my late answer. Unfortunately I cannot read those characters, but I think the call stack can be found in one of the following tabs:
![Screenshot](https://user-images.githubusercontent.com/17685000/230513265-68111589-33bb-4f93-aa4c-e56c9791119c.png)
Could you please check those tabs and if you see a list of function calls similar to the example I shared in https://github.com/armory3d/armory/issues/2831#issuecomment-1492742754 share a screenshot of that?

**Comment by chuiliuyiyi** [comment] 2023-04-13 02:42
Read prefs: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Running Armory SDK from D:\ArmorySDK2304\armsdk/
Read blend: E:\aaa\untitled.blend
Using CPU for environment render (might be slow). Enable CUDA if possible.
Saved: 'E:\aaa\build_untitled\compiled\Assets\envmaps\env_World.jpg'
 Time: 00:00.26 (Saving: 00:00.02)

D:\ArmorySDK2304\armsdk/nodejs/node.exe D:\ArmorySDK2304\armsdk/Kha/make krom --ffmpeg D:\Program Files\python3.8.3\Scripts\ffmpeg.EXE -g direct3d11 --shaderversion 330 --parallelAssetConversion 4 --to build_untitled/debug --quiet --nohaxe --noproject
D:\ArmorySDK2304\armsdk/Kha/Tools/windows_x64/haxe.exe --connect 6000 project-krom.hxml
Finished in 5.973s
D:\ArmorySDK2304\armsdk/Krom/Krom.exe E:\aaa\build_untitled/debug/krom E:\aaa\build_untitled/debug/krom-resources --consolepid 6936
WARNING: Player exited code 2147483651


![image](https://user-images.githubusercontent.com/75259241/231634268-8154504d-ff7b-43e2-a445-3f5ebf1fb156.png)

**Comment by chuiliuyiyi** [comment] 2023-04-13 02:43
The code output after clicking play

**Comment by MoritzBrueckner** [comment] 2023-04-15 14:23
> Could you please check those tabs and if you see a list of function calls similar to the example I shared in https://github.com/armory3d/armory/issues/2831#issuecomment-1492742754 share a screenshot of that?

Can you please try this (see my post above)? The output from Visual Studio might show the reason for the crash, unlike the Blender console output which in this case only gives background information.

**Comment by MoritzBrueckner** [comment] 2023-04-23 19:44
My answer to https://github.com/armory3d/armory/issues/2831#issuecomment-1509995738 (let's continue here in this issue):

In https://github.com/armory3d/armory/issues/2832#issuecomment-1499765979 you can see in the screenshot where to click in Visual Studio (highlighted in red), one of the tabs should look very similar to my screenshot in https://github.com/armory3d/armory/issues/2831#issuecomment-1492742754. Please try to find this and then screenshot it, otherwise there is not much I can do since I cannot reproduce it myself.

**Comment by chuiliuyiyi** [comment] 2023-04-24 04:26
![image](https://user-images.githubusercontent.com/75259241/233899716-c34c804d-c83e-40e9-8275-e467e7491fe9.png)
![image](https://user-images.githubusercontent.com/75259241/233899740-0714319e-d42b-4750-8a6f-f84b808229f1.png)
![image](https://user-images.githubusercontent.com/75259241/233899752-a573f5d4-d3ec-4471-93e0-5d5077f09d81.png)
![image](https://user-images.githubusercontent.com/75259241/233899773-72740f6d-1ab2-4f3c-b489-357aef32061f.png)
![image](https://user-images.githubusercontent.com/75259241/233899792-2a2e1f3d-28ed-4d09-af27-5bee810b7d9c.png)
![image](https://user-images.githubusercontent.com/75259241/233899816-a02efa35-1d85-4013-a938-6e04e9cee1d5.png)
“untitled_1_0_2.exe”(Win32): 已加载“E:\aaa\build_untitled\windows-hl-build\x64\Debug\untitled_1_0_2.exe”。已加载符号。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\apphelp.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ws2_32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\dinput8.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\crypt32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\winmm.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\winhttp.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\sechost.dll”
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\dbghelp.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\InputHost.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\CoreMessaging.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\WinTypes.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\CoreUIComponents.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\propsys.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ntmarta.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\kernel.appcore.dll”
Starting KincHL
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\dbgcore.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\ResourcePolicyClient.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\ResourcePolicyClient.dll”
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\aticfx64.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\version.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\dwmapi.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\dwmapi.dll”
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\atiuxp64.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\atidxx64.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\setupapi.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。无法查找或打开 PDB 文件。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\amdihk64.dll”。模块已生成，不包含符号。
“untitled_1_0_2.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。无法查找或打开 PDB 文件。
D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG
0x00007FFD9E1C3E49 处(位于 untitled_1_0_2.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000B8B66FA978 处。
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\shlwapi.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\amdihk64.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\setupapi.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\cfgmgr32.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\atidxx64.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\atiuxp64.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\version.dll”
“untitled_1_0_2.exe”(Win32): 已卸载“C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\aticfx64.dll”

**Comment by chuiliuyiyi** [comment] 2023-04-24 04:28
Please.

**Comment by chuiliuyiyi** [comment] 2023-04-24 22:13
Many other game engines can run on my computer, can they support graphics card free mode? After all, there are many computers that use integrated graphics cards.

**Comment by chuiliuyiyi** [comment] 2023-05-04 23:04
My graphics card is shared memory. I set aside a part of the memory card to be used as a graphics card. I don't know whether it is an integrated graphics card.

**Comment by MoritzBrueckner** [comment] 2023-05-05 12:09
Please keep in mind what I wrote above: This is almost certainly _not_ an Armory issue but a Kinc issue, so you will need to test whether you can reproduce the crash in a Kinc application (since the crash seems to depend your hardware) and then eventually open a bug report on the Kinc repository that I linked above. Please also share your exact hardware specifications if you create a bug report in that repository. If you cannot reproduce the crash with a Kinc example then we can continue investigating on the Armory side of things.

I'm sorry, but without more testing and/or information from your side it will be very difficult to fix your issue. For now I will close this issue, but we can reopen it if it actually turns out to be Armory-related only.

**Closed by MoritzBrueckner** 2023-05-05 12:09 UTC
Labels: bug

**Comment by chuiliuyiyi** [comment] 2023-05-05 12:49
What I mean is, my computer doesn't have a graphics card and it's an AMD CPU. Can I have the Armory support computers without graphics cards.
What I mean is, my computer doesn't have a graphics card and it's an AMD CPU. Can I have the Armory support computers without graphics cards.

好甜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "armory3d/armory"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [armory3d/armory] Is the flash past due to a memory graphics card? (Issue #2832)





 
Please keep in mind what I wrote above: This is almost certainly not an Armory issue but a Kinc issue, so you will need to test whether you can reproduce the crash in a Kinc application (since the crash seems to depend your hardware) and then eventually open a bug report on the Kinc repository that I linked above. Please also share your exact hardware specifications if you create a bug report in that repository. If you cannot reproduce the crash with a Kinc example then we can continue investigating on the Armory side of things.
 
I'm sorry, but without more testing and/or information from your side it will be very difficult to fix your issue. For now I will close this issue, but we can reopen it if it actually turns out to be Armory-related only.

**Comment by MoritzBrueckner** [comment] 2023-05-05 13:02
Yes, if you try to reproduce your issue in Kinc and then report it to the Kinc repository. Otherwise Robert (the Kinc developer) doesn't know that this needs to be fixed.

**Comment by chuiliuyiyi** [comment] 2023-05-05 13:07
How can we reproduce the problem of kinc? There are no related error reports on the Blender console, and only one breakpoint was marked in the compiled C++file, and there are no error reports.
&nbsp;


好甜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Moritz ***@***.***&gt;; 
发送时间: 2023年5月5日(星期五) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [armory3d/armory] Is the flash past due to a memory graphics card? (Issue #2832)





 
Yes, if you try to reproduce your issue in Kinc and then report it to the Kinc repository. Otherwise Robert (the Kinc developer) doesn't know that this needs to be fixed.

**Comment by MoritzBrueckner** [comment] 2023-05-06 13:06
> How can we reproduce the problem of kinc?

You need to fork the Kinc samples repository I linked above, and then follow the instructions in the repository readme (note that the git URL in the readme is wrong, but the **Build and Run Example** step should be correct). This has nothing to do with Blender or Armory, Kinc is basically the backend implementation that Armory is built upon.

**Comment by RobDangerous** [comment] 2023-05-06 16:46
You might be on the wrong track here. Zeta found this in the pics above:
```D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG
```
D3D11_CREATE_DEVICE_DEBUG is only set in debug-mode so that won't happen in Armory.

**Comment by MoritzBrueckner** [comment] 2023-05-08 14:51
> D3D11_CREATE_DEVICE_DEBUG is only set in debug-mode so that won't happen in Armory.

In the images above you can see that they built the project in debug mode, so I guess it's a wrong local setup then like Zeta mentioned on Discord.

@chuiliuyiyi In the Visual Studio installer, please install the Windows 10 SDK i if not present **and also** a package called "Graphics Tools" or similar (this might be translated into your language in some way). This could potentially fix your issue.

**Comment by RobDangerous** [comment] 2023-05-08 15:06
This will not fix the original issue because D3D11_CREATE_DEVICE_DEBUG is not set in Release mode. But the original issue might reveal itself afterwards. Or just run it in Release mode in Visual Studio.
