### ISSUE TITLE
Krom Player SDK1909 crashing

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1365] opened 2019-09-02 11:29 UTC
**Description**
Krom testing player is crashing with certain projects using new SDK1909.
Resulting in the white screen of death and crash on Krom.
I often receive a proper windows error from time to time:

	the exception breakpoint has been reached
	(0x800000003) occurred in the application in the application at location 
	0x00007FF67BC12F67

while using the Krom Runtime Browser is fine.

**To Reproduce**
try with an old project, the instancing example  for example : armory_examples\instancing
Steps to reproduce the behavior.
Open the file and hit F5 to run the Krom player.

**Expected behavior**
the player is launching correctly instead of crashing.

**System**
Blender : 2.80 (sub 75), branch: official master, commit date: 2019-07-29 14:47
Armory : ArmorySDK1909
OS : Windows 10 pro version 1903
Graphics card: Intel HD Graphics 620

**Test File**
https://github.com/armory3d/armory_examples/blob/master/instancing/inst.blend

**Comment by swimming92404** [comment] 2019-09-02 11:49
me too, I opened my project and it crashed with windows mode

**Comment by zeeshan595** [comment] 2019-09-25 22:05
I can't reproduce this issue on my machine. Could you check if this issue is still occurring for you?

Blender: 2.80
OS: Linux (Manjaro)
Graphics: AMD Vega 64

**Comment by onelsonic** [comment] 2019-09-27 15:40
SDK1909 is still creating the issue - the dev 'unstable' version seems better but no sound in Krom.

**Comment by luboslenco** [comment] 2019-10-02 20:06
Fixed instancing crash in `ArmorySDK-2019-10`. Please download the fresh build from itch.io and install the latest `armory.py` which is included in `ArmorySDK-2019-10.zip` before updating the sdk using the built-in updater.

**Closed by luboslenco** 2019-10-02 20:06 UTC
Labels: bug
