### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by SchaluKid** [armory3d/armory#2197] opened 2021-05-16 09:33 UTC
Thank you for contributing to Armory!

**Description**
If I start the Armory player, I just get a black Screen, but not if I use a template.

**To Reproduce**
Make a custom game and play it with the Armory player

**Expected behavior**
Testing the game

**System**
Blender: 2.83 LTS
Armory: Newest
OS: Windows 10
Graphics card: Who knows?

**Test File**
[ErsterVersuch(ObDasKlappt).zip](https://github.com/armory3d/armory/files/6488976/ErsterVersuch.ObDasKlappt.zip)

**Comment by MoritzBrueckner** [comment] 2021-05-18 18:21
Hi, I just tested your file and I can't reproduce it. With latest Armory you mean the latest monthly SDK release or the latest master branch (Git version)? For the Git version, please make sure to use the soon to be released Blender 2.93 LTS, the next monthly SDK will also require that.

Are there any error messages and/or warnings in the console?

**Comment by SchaluKid** [comment] 2021-05-19 05:34
Thank you for the information! There aren't any errors or warnings, I think it is because i don't have a that big graphics card.

**Comment by SchaluKid** [comment] 2021-05-19 16:24
Thank you very much!

**Comment by MoritzBrueckner** [comment] 2021-05-19 17:34
@SchaluKid did that resolve your issue? Otherwise please check if the browser itself shows some warnings in the developer panel (`Ctrl + Shift + I` in Firefox and probably also in Chrome and other browsers). Depending on how old your graphics hardware is, compiling with legacy shaders enabled might help (the setting can be found in the Armory preferences).

**Comment by SchaluKid** [comment] 2021-05-20 06:07
Ok, thank you!

**Comment by MoritzBrueckner** [comment] 2021-06-26 21:59
@SchaluKid Hi, were you able to either fix the issue yourself or get more information about it? Does the same error happen if you start the game with Krom (and not in the browser)? Otherwise I think there is not much we can do, maybe try out Blender 2.93 and the latest Armory SDK.

**Comment by MoritzBrueckner** [comment] 2021-07-04 19:59
@SchaluKid please reopen if the issue still persists. I'm closing this because the issue could not be reproduced so far.

**Closed by MoritzBrueckner** 2021-07-04 19:59 UTC
Labels: bug
