### ISSUE TITLE
Just few bug pictures

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#2136] opened 2021-03-19 02:34 UTC
hi just wanted to try armory again and did on LTS and finding all times bugs . i too lazy to put blend file or any other except these screenshot because i think this is too obvious for devs to not find such bgus themself. anyway ill wait again for many more month untill i try armory again to see its its bugfree mostly and at least not every time crashing live patch armory session. good bye

![ARMORY BUGSS](https://user-images.githubusercontent.com/9019563/111723358-acf7e880-8863-11eb-893e-a7d3b9684def.jpeg)
![Armory Bug after remesh modifier](https://user-images.githubusercontent.com/9019563/111723360-ad907f00-8863-11eb-8bd3-0c1c7f346bf9.jpeg)
![Armory Bug if not unchecked export tangents](https://user-images.githubusercontent.com/9019563/111723361-ad907f00-8863-11eb-9726-a43ccfaa48fb.jpeg)
![Armory Bugs](https://user-images.githubusercontent.com/9019563/111723363-ae291580-8863-11eb-9f04-0c903a25a31c.jpeg)

**Comment by N8n5h** [comment] 2021-03-19 12:59
From the second and third pic it seems you encountered this issue: https://github.com/armory3d/armory/issues/1411#issuecomment-536114520, which you can workaround it by not having n-gons (faces with more than 4 vertices) if you are using some kind of normal mapping. 

The other seems to be related to materials, and (since there is no file to confirm it) I guess that it may have to do with some unsupported node: https://github.com/armory3d/armory/wiki/supported_nodes.

**Comment by MoritzBrueckner** [comment] 2021-04-02 18:33
@mushroomeo Thanks for the report. It would help a lot if you could upload the blend files anyway as it makes things a lot simpler. The error messages that weren't fixed in the linked PR (see above) are so generic that without a file it's difficult to see what went wrong. The `TBN` matrix for example that is mentioned in one of the error messages occurs in every shader with normal maps for example, so there is a lot that can go wrong there. 

> i too lazy to put blend file or any other except these screenshot because i think this is too obvious for devs to not find such bgus themself

I think you underestimate how diffcult it is to check every possible combination of nodes that could somehow break. Many nodes are just not completely supported and the code is written by many people, so it is actually pretty likely that there are many bugs and situations one forgets when testing. If it would be so simple, there wouldn't be any bugs.
Also, a simple looking bug can be caused by some setting on the user side that looks completely unrelated at first, so it's always best to upload a minimal blend file.

Of course you can be lazy and don't upload a blend file, but then please don't expect the bug(s) to be fixed soon.

**Comment by MoritzBrueckner** [comment] 2022-03-09 21:55
The `sssWidth` error from the first screenshot is now potentially fixed, one error was fixed by @ N8n5h in a PR linked above and I couldn't reproduce the other one (with `TBN` in the error message). While trying to reproduce it, I found another bug and fixed it (https://github.com/armory3d/armory/pull/2454), but without any example files we can't do more here so I will close this issue now.

**Closed by MoritzBrueckner** 2022-03-09 21:55 UTC
Labels: bug, material nodes
