### ISSUE TITLE
new scene shows old scene?!

### ISSUE THREAD

**Issue by zartan9** [armory3d/armory#2048] opened 2020-12-06 05:18 UTC
![scene](https://user-images.githubusercontent.com/74879950/101272244-5e14c000-3758-11eb-9701-2c9e760879b7.png)
hi im still very new but making progress (found out how to go to new scene on collision!)... but the remnants of the old scene shows even though i removed active and loaded new one...any advice. PS is there a "restart scene" node to replay a level? thanks!

**Comment by QuantumCoderQC** [comment] 2020-12-07 10:04
Hi @zartan9 If you enable Debug console for Armory, you could clearly see what objects were removed and what was added.

The issue here is I believe the remove scene trait removes the trait itself. Hence, after remove scene, nothing runs anymore. You may test if this is the case by adding a simple print node after the remove scene node.

A way to re-start the scene:
![image](https://user-images.githubusercontent.com/55564981/101337337-ce683200-387b-11eb-9ccd-15448a0c35f8.png)

Hope this helps,

Best regards,
QC

**Comment by zartan9** [comment] 2020-12-08 06:35
hi, its odd cause when i publish to web the scene seems to change alright! anyway,, trying your node set up works to replays the current scene great! for "print" node what am i typing for string? thanks!

**Comment by zartan9** [comment] 2020-12-16 05:31
the debug 
![Uploading scene1.png…]()
shows only the 2 cylinders but i can plainly see the box from the prior scene. is there a refresh node or something?

**Comment by MoritzBrueckner** [comment] 2020-12-16 08:04
Can you maybe share the blend file? This makes it much easier to see what's wrong and if it's a bug we have a good reproducible example. Thanks

**Comment by zartan9** [comment] 2020-12-16 21:22
great idea! ok here it is.. 2.83 im using... when spin the scene (spacebar etc) and the ball touches plain it goes to next scene. thanks!
[object_rotate.zip](https://github.com/armory3d/armory/files/5705555/object_rotate.zip)

**Comment by MoritzBrueckner** [comment] 2020-12-17 08:02
It looks like the problem is that the scene to which the game changes has no camera. For me it shows just black without a camera and when adding a camera everything works as expected for me.

**Comment by zartan9** [comment] 2020-12-17 19:33
hi i added a camera and the previous scene is still showing... can you send a blend file that works on your end too? also how to  see which drivers i need for armory? screenshot below. Thank you.
![camera](https://user-images.githubusercontent.com/74879950/102534205-616f4c00-4074-11eb-8ef2-73051aa70486.png)

**Comment by MoritzBrueckner** [comment] 2020-12-17 20:38
The scene you sent works perfectly fine for me that's why I thought it might be your graphics card that's creating this issue. There is no special driver version required for armory but it could help to try updating your graphic card drivers to the latest version. 

Also, what SDK version do you use? Because it looks like the screen isn't properly cleared between frames, can you please check if you have `Properties Panel > Armory Render Path > World > Background` set to `World` or `Clear`?

**Comment by zartan9** [comment] 2020-12-17 22:42
Yes amory render path is set to world (I tried clear, then it went blank). Maybe there is another conflict in the armory exporter (it says arm).. the sdk armory notes say: 2019-06-30.

**Comment by MoritzBrueckner** [comment] 2020-12-17 22:50
> the sdk armory notes say: 2019-06-30.

That's a very old SDK version, you should download the latest version (2020.12) and try it again: https://armory3d.org/download.html

> Maybe there is another conflict in the armory exporter (it says arm).

Is there some error message or what do you mean with "it says arm"? "arm" is quite often used in the code as an abbreviation for Armory.

**Comment by zartan9** [comment] 2020-12-18 00:28
hi i updated to latest thank you. I cant hold down letter g now i have to keep hitting it (due to update?!) and the objects dont move in edit mode and xyz is unlocked, this is odd I cant reposition my cube! Anyway same result on new scene..i envision a game with tons of scenes/levels so once this is figured out ill be on the right track..
No error message I get a warning (now?) saying open console not sure how to do that...

**Comment by MoritzBrueckner** [comment] 2020-12-18 14:54
Yes that is probably due to an update with missing node replacement information (the keyboard nodes were updated and usually there is an update routine that keeps compatibility with old files, but not in this case).

You can open the console in Blender (on Windows) via `Window > Toggle System Console`.

I tested it again with the default camera and now I get the same results. It looks like some render targets are no longer cleared on both deferred and forward render paths when the scene is changed. This happens because the second scene has no world at all, so there is nothing rendered as the background and the previous frames are still visible.

@luboslenco Should we default to clearing `gBuffer0` when a scene has no world (only for that scene of course, not via conditional compilation)?

**Comment by zartan9** [comment] 2020-12-18 20:19
hi the switch to down worked! easiest thing yet! Great.Now I found debug console like you said and i attached screenshot. i dont understand some of it... but "Some files in the build folder are locked" could that be why i cant move my cube? I dont know how i locked it. also says no active camera...hope this screenshot helps..
![console](https://user-images.githubusercontent.com/74879950/102657820-626fae80-4144-11eb-9e58-284f3f9e39b9.png)

**Comment by MoritzBrueckner** [comment] 2020-12-18 21:08
That's just the "regular" Blender console, the "debug console" is [something different](https://github.com/armory3d/armory/wiki/debug#debug-console) (but you found the right thing, the debug console is for other purposes).

What this message tells you is that some of the files that are used while exporting the game are opened in some other program that locked them (might be a text editor for example). So Armory can't write to them. Try to find the application that locked the file and close it.

The error below that looks pretty ugly but it happens usually when some data is changed while exporting, for example if you hit `Clean` while a build is running or if you edit the blend file during the build process. It can also be a result of the above warning, so always try to get rid of that first.

However, this is not related to the scene switch, the issue is the missing world in the second scene as described above. I'm just waiting for Lubos to answer which solution we should choose and then it will be fixed as soon as possible :) You should just add a world to the second scene and everything will work.

**Comment by zartan9** [comment] 2020-12-24 07:12
Hey adding world worked thanks. I'll look into other issues open new issue for write/read nodes to load save levels. Armory game engine has advance features just finding it takes some time.  Keep gaming.

**Comment by luboslenco** [comment] 2020-12-29 10:44
If `Properties Panel > Armory Render Path > World > Background` is set to `World` then we should probably print a warning if there is no world, since in that case clearing is done via drawing a world skydome. If it's set to `Clear` then we just do regular buffer clear all the time.

**Closed** 2020-12-31 15:29 UTC
Labels: bug
