### ISSUE TITLE
Crash when playing viewport a rigged character 

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#139] opened 2017-02-20 15:22 UTC
I've imported the character and tried to play it, but it immediatly crash.
here is the blend file

http://pasteall.org/blend/index.php?id=45630

**Comment by luboslenco** [comment] 2017-02-28 21:50
He seems to agree the issue is now fixed. Thanks for report - caught several bugs here! Fix will be included in the next build.

![](https://gifyu.com/images/ScreenflickMovie.gif)

**Closed by luboslenco** 2017-02-28 21:50 UTC
