### ISSUE TITLE
UI buttons not clickable after publish

### ISSUE THREAD

**Issue by tachikaS** [armory3d/armory#1122] opened 2019-01-26 14:51 UTC
Hello,
i have some problems with the UI Canvas after publishing my scene at Armory 0.6 Beta. In the Armory  Player all buttons are working fine and there a no problems. Also there are no errors when debugging the scene. After publish it for Windows(Krom) or HTML5 all Canvas buttons are visible but not clickable. I have tried this with my own build, with the ui_canvas example and the Twin Stick Demo. Everywhere the same problem. I tried to publish with my Laptop and my PC (Both win 10, 64 bit)  but nothing changed. Is there anything i need to pay attention with the Canvas UI before publish the application?

**Comment by luboslenco** [comment] 2019-02-11 14:40
Hi, thanks for posting an issue about this! It was a bug caused by dead-code-elimination. I pushed a fix at https://github.com/armory3d/zui/commit/c10bdb70ef13395cb08edd837d2d715c4701481a.

**Closed by luboslenco** 2019-02-11 14:40 UTC
