### ISSUE TITLE
Call Group repeats unnecessarily at the end

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#1673] opened 2020-04-21 08:19 UTC
**Description**
Call Group repeats unnecessarily at the end

**To Reproduce**
```
armory.logicnode.PrintNode:13: Main: start
armory.logicnode.PrintNode:13: GroupTest: start
armory.logicnode.PrintNode:13: Main: end
armory.logicnode.PrintNode:13: GroupTest: start
```

**Expected behavior**
```
armory.logicnode.PrintNode:13: Main: start
armory.logicnode.PrintNode:13: GroupTest: start
armory.logicnode.PrintNode:13: Main: end
```

**System**
Blender: 2.81a
Armory: 2004 Update Git 21.04.2020
OS: Linux Mint 19.3 Cinnamon
Graphics card: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

**Test File**
[callgrouptest2.blend.zip](https://github.com/armory3d/armory/files/4508635/callgrouptest2.blend.zip)

![image](https://user-images.githubusercontent.com/39986875/79843250-50255100-83ba-11ea-8cdc-906e7239fa72.png)

**Comment by knowledgenude** [comment] 2020-04-21 13:08
Hi, @Dzynek! Hope i can help you!

The issue is not in Call Node Group but in On Init node. I think that the issue is caused by having two On Inits being actived in almost the same time.

Here is the file without Call Node Group having the same issue.

[callgrouptest3.zip](https://github.com/armory3d/armory/files/4510123/callgrouptest3.zip)

I think you should put a On Event input on the Group node instead of a On Init, and call the event after calling the group node to activate it.

**Comment by Dzynek** [comment] 2020-04-21 14:37
Hi knowledgenude

> Here is the file without Call Node Group having the same issue:
> [callgrouptest3.zip](https://github.com/armory3d/armory/files/4510123/callgrouptest3.zip)
```
armory.logicnode.PrintNode:13: Main: start
armory.logicnode.PrintNode:13: Main: end
armory.logicnode.PrintNode:13: GroupTest: start

```
For me your example (callgrouptest3.zip) works fine

**Comment by Dzynek** [comment] 2020-04-21 14:52
I think there is an additional problem because Main Trait (Print end) should probably wait until GroupTest Trait ends?
```
armory.logicnode.PrintNode:13: Main: start
armory.logicnode.PrintNode:13: Main: end
armory.logicnode.PrintNode:13: GroupTest: start
armory.logicnode.PrintNode:13: GroupTest: start
```
![image](https://user-images.githubusercontent.com/39986875/79880327-26871c80-83f0-11ea-8830-e005b69d49f1.png)

[callgrouptest2.blend.zip](https://github.com/armory3d/armory/files/4510716/callgrouptest2.blend.zip)

**Comment by knowledgenude** [comment] 2020-04-21 15:22
There is not an additional issue, because the node output will return True when it is activated. The only output that return True **just when it is "finished",** is the output named 'Done' (like the one we see in Timer node).

This print you have send now, is showing the message i got printed in my console using the Add Trait.

I really think that the problem is with On Init being used two times in sequence, i will test it more and try to give a better answer.

**Comment by knowledgenude** [comment] 2020-04-21 16:00
The file I sent you was not the correct one. Maybe I forgot to save, but I had basically replaced the Call Group with an Add Trait and got the same result (even without using the Call Group).

But now I have found a better way to experience the problem. In this file I basically use a boolean to limit the On Init to returning the value only once and doing that, apparently the logic works as you wish. So, maybe the issue is really with On Init node.

Test file:
[callgrouptestworking.zip](https://github.com/armory3d/armory/files/4511104/callgrouptestworking.zip)

**Comment by Dzynek** [comment] 2020-04-24 14:39
Thank you for your help

To simplify, I created Only Once Node.

Download it from: http://www.dzynek.pl/armory3d/15-onlyoncenode
![image](https://user-images.githubusercontent.com/39986875/80224032-701e7400-8649-11ea-904a-08c9451ab5b4.png)

Another question is what is Node Group Output? He gives nothing.

greetings

**Comment by knowledgenude** [comment] 2020-04-24 15:27
I really don't have any understanding about node groups, because i don't have  used it until this moment. But i will assume that the function of nodes group is to armory recognize a "node chain" as a group.

For me, if you call a Node Group, only the chain that have a Node Group Output will be called.

In this link, a guy have explained the node group: https://forums.armory3d.org/t/node-groups/1402/2

Anyway, i prefer to call the "nodes chain"  using global event node, it is more organized in my view, as the event name can be more sugestive for me.

Also, maybe you could make a pull request for the node you do, because is great to have many node options.

I will take a day to update the Armory nodes tutorials and Armory examples for beginners,  it will not take too much time and now is the only thing i can do for Armory because i don't know Haxe :/. I am just waiting to end a short project.

So, i really hope that i have helped you in something!  Have a great day, @Dzynek!

**Comment by Dzynek** [comment] 2020-04-24 19:03
I wonder what is "Node Group Output" for?
![image](https://user-images.githubusercontent.com/39986875/80247532-812dac00-866e-11ea-8630-cd3927362d69.png)

Whether I put it in, for example, GroupTest or not, I don't see it doing anything

In the Haxe code it also does nothing but I also can't know Haxe
```
package armory.logicnode;

class GroupOutputNode extends LogicNode {

	public function new(tree: LogicTree) {
		super(tree);
	}

	override function run(from: Int) {
		runOutput(0);
	}
}
```

**Comment by knowledgenude** [comment] 2020-04-24 20:37
Here is the code of Loop Break node, it looks almost the same. Maybe do almost the same too, but i don't understand none of both nodes, then i can't make any afirmative. 👎 

    package armory.logicnode;

    class LoopBreakNode extends LogicNode {

	     public function new(tree: LogicTree) {
		     super(tree);
	     }

	     override function run(from: Int) {
		     tree.loopBreak = true;
	     }
    }

**Comment by knowledgenude** [comment] 2020-07-04 17:25
I will close this and open an issue about lack of documentation in certain nodes, but as i am able to write the documentation for it, probably i will do soon.

**Closed by knowledgenude** 2020-07-04 17:25 UTC
Labels: bug
