### ISSUE TITLE
[Android] - object instancing not working on Android

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2322] opened 2021-09-05 18:39 UTC
I checked and objects instancing is not working on Android.
Objects are in the scene but not rendered.

Similar to https://github.com/armory3d/armory/issues/2212

Armory Instancing : https://github.com/armory3d/armory/wiki/instancing

To test this I put two files together :

    the main file is scene.blend
    the assest library bank file is : libraryassests.blend

Download the files here : https://github.com/onelsonic/armory_tests/blob/master/linkedinstancing.7z

![Animation](https://user-images.githubusercontent.com/53947594/119418591-9d2fd100-bcf8-11eb-855c-317d57deb779.gif)

**Comment by QuantumCoderQC** [comment] 2021-09-06 11:09
Seems to be a duplicate of #1536

**Comment by MoritzBrueckner** [comment] 2021-09-06 11:36
Closing in favor of #1536.

**Closed by MoritzBrueckner** 2021-09-06 11:36 UTC
Labels: bug

**Comment by onelsonic** [comment] 2021-09-08 14:44
thanks I did not see this one
