### ISSUE TITLE
Material does not show in Krom - maybe related to UV Map node / cache?

### ISSUE THREAD

**Issue by rossoe** [armory3d/armory#1317] opened 2019-07-14 16:52 UTC
### SHORT DESCRIPTION:
After loading in a terrain mesh (.asc heightmap) and sat image using **BlenderGIS** addon - Krom does not display the material, even though it shows up fine in viewport.

It does not appear to be just the node itself but possibly related to socket connections doing something with cache?

### EXPECTED RESULT:
Load terrain mesh, drape sat image over mesh, play Krom and see image
![image](https://user-images.githubusercontent.com/28996048/61186258-2a189680-a65b-11e9-86cf-9d57ff74d00a.png)
![image](https://user-images.githubusercontent.com/28996048/61186319-baef7200-a65b-11e9-9b22-861b98ff2b74.png)

### ACTUAL RESULT:
_What happens right now that's different from how you expect or want it to work?_
Loading of the terrain and sat looks fine from viewport:
![image](https://user-images.githubusercontent.com/28996048/61186258-2a189680-a65b-11e9-86cf-9d57ff74d00a.png)

But then will not load the material in Krom play -
![image](https://user-images.githubusercontent.com/28996048/61186242-f0479000-a65a-11e9-8474-54bb603d0bb4.png)

Only error showing in the console is:
`iron.data.Geometry:271: Armory Warning: Geometry square20_1_1 is missing UV map`

### STEPS TO REPRODUCE:
_Please list clear, step by step instructions to replicate the result you got. For a feature request list the steps to use the feature._

We discovered that by removing the UV Map from within Shader editor, and then running 'clean' on the project - the material shows up again in Krom play!
![image](https://user-images.githubusercontent.com/28996048/61186373-4ec13e00-a65c-11e9-871f-c4aec9835c7e.png)

**Steps to create same scenario:**
1. Load .asc (terrain heightmap) using BlenderGIS
2. load jpg sat image using BlenderGIS
3. setup camera etc - press play for Krom

**Steps to reproduce issue on below test file:**
1. Press Krom play - see no material
2. select section of terrain with material seen in viewport
3. goto Shader editor
4. remove UV Map node
5. run 'clean' on project
5. run Krom play again and material returns.

If I add the UV Map node back in - it continues to work and display the material!

### TECHNICAL SPECIFICATIONS:
What version(s) of the following did you try:
Blender: 2.8beta  (5th July build)
Armory: 0.7.0 (latest SDK update)
Operating system: Win 10
Graphics card & driver: GTX-960 latest Nvidia driver

### TEST FILE TO REPRODUCE:
_Please create the simplest file possible that demonstrates the issue:_
https://1drv.ms/u/s!AjCedBZJ5Eh4jCBYqxegNBJB1nyA?e=A6aOTv
38mb blend file

**Comment by N8n5h** [comment] 2019-12-13 16:20
The issue seems to be related to https://github.com/armory3d/armory/issues/1378, a fix has been commited to solve that one. Can you try to reproduce this issue in the latest version of Armory to see if it's still present? since the test file is unavailable.

**Comment by luboslenco** [comment] 2019-12-21 12:16
Feel welcome to reopen if issue persists.

**Closed by luboslenco** 2019-12-21 12:16 UTC
